In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
url = '/content/drive/MyDrive/Colab Notebooks/apart/report.txt'

marry = pd.read_csv(url,error_bad_lines=False,sep='\t')
marry.head()

     기간 자치구  월별      혼인      이혼
0  2015  합계   계  64,193  18,176
1  2015  합계  1월   5,901   1,526
2  2015  합계  2월   4,488   1,246
3  2015  합계  3월   5,665   1,425
4  2015  합계  4월   5,313   1,510

In [3]:
marry.drop('이혼',axis=1,inplace=True)

In [10]:
marry=marry[marry['자치구']!='합계']

In [12]:
marry=marry[marry['월별']!='계']

In [15]:
marry['월별']=marry['월별'].str[:-1]

In [20]:
marry=marry[['기간','월별','자치구','혼인']]

In [26]:
marry=marry.rename({'기간':'year','월별':'month','자치구':'Gu','혼인':'marriage'},axis='columns')

In [27]:
marry

      year month   Gu marriage
14    2015     1  종로구       67
15    2015     2  종로구       56
16    2015     3  종로구       71
17    2015     4  종로구       55
18    2015     5  종로구       69
...    ...   ...  ...      ...
2023  2020     8  강동구      182
2024  2020     9  강동구      155
2025  2020    10  강동구      180
2026  2020    11  강동구      202
2027  2020    12  강동구      252

[1800 rows x 4 columns]

In [31]:
marry.month=marry.month.astype(int)
marry.marriage=marry.marriage.astype(int)

In [32]:
marry.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1800 entries, 14 to 2027
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   year      1800 non-null   int64
 1   month     1800 non-null   int64
 2   Gu        1800 non-null   object
 3   marriage  1800 non-null   int64
dtypes: int64(3), object(1)
memory usage: 150.3+ KB

In [59]:
marriage_avg=[]
for avg in range(len(marry.month)):
    if marry.month.iloc[avg] in [1,3,5,7,8,10,12]:
        marriage_avg = marry.marriage/31
    elif marry.month.iloc[avg] in [4,6,9,11]:
        marriage_avg = marry.marriage/30
    else:
        marriage_avg = marry.marriage/28

In [58]:
marry.month.iloc[0]

1

In [60]:
marriage_avg

14      2.161290
15      1.806452
16      2.290323
17      1.774194
18      2.225806
          ...
2023    5.870968
2024    5.000000
2025    5.806452
2026    6.516129
2027    8.129032
Name: marriage, Length: 1800, dtype: float64

In [61]:
marry['avg']=marriage_avg

In [62]:
marry

      year  month   Gu  marriage       avg
14    2015      1  종로구        67  2.161290
15    2015      2  종로구        56  1.806452
16    2015      3  종로구        71  2.290323
17    2015      4  종로구        55  1.774194
18    2015      5  종로구        69  2.225806
...    ...    ...  ...       ...       ...
2023  2020      8  강동구       182  5.870968
2024  2020      9  강동구       155  5.000000
2025  2020     10  강동구       180  5.806452
2026  2020     11  강동구       202  6.516129
2027  2020     12  강동구       252  8.129032

[1800 rows x 5 columns]

In [63]:
marry.to_csv('/content/drive/MyDrive/Colab Notebooks/apart/marry.csv',index=False)