In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import os
from selenium import webdriver 
import time 
import pandas as pd 

webdriver_path = os.getcwd()+'.//webdriver//chromedriver.exe'

url_base = 'https://www.koreabaseball.com/Record/Player/' 
category_list = ['HitterBasic/Basic1.aspx', 'Defense/Basic.aspx'] 
driver = webdriver.Chrome(webdriver_path) 
driver.implicitly_wait(3) 
# driver.maximize_window() 

# 드라이버 열기
driver.get(url_base+category_list[0])

# 정규시즌으로 페이지 넘김
driver.find_element_by_class_name('select02').click()
xpath_format = '//option[@value="0"]'
driver.find_element_by_xpath(xpath_format).click()
time.sleep(0.5)

# Dataframe으로 변환
temp_list = [x.split(' ') for x in driver.find_element_by_tag_name('table').text.split('\n')] 
temp_data = pd.DataFrame(columns = temp_list[0]) 
for i,temp in enumerate(temp_list[1:]): 
    # 투수 기록 대비
    try: 
        temp_data.loc[i] = temp 
        time.sleep(0.5) 
    except: 
        ip_index = temp_list[0].index('IP') 
        ip = temp[ip_index] 
        del temp[13] 
        temp[13] = ip+' '+temp[13] 
        temp_data.loc[i] = temp 
        time.sleep(0.5)

baseball_data = temp_data.copy()
# 넥스트 버튼 누르기
driver.find_element_by_class_name('next').click()
# Dataframe으로 변환
temp_list = [x.split(' ') for x in driver.find_element_by_tag_name('table').text.split('\n')] 
temp_data = pd.DataFrame(columns = temp_list[0]) 
for i,temp in enumerate(temp_list[1:]): 
    # 투수 기록 대비
    try: 
        temp_data.loc[i] = temp 
        time.sleep(0.5) 
    except: 
        ip_index = temp_list[0].index('IP') 
        ip = temp[ip_index] 
        del temp[13] 
        temp[13] = ip+' '+temp[13] 
        temp_data.loc[i] = temp 
        time.sleep(0.5)
    

baseball_data_test = pd.merge(baseball_data,temp_data,on = ['순위','선수명','팀명','AVG'])
# x_path 만들기
xpath_format = '//*[@id="cphContents_cphContents_cphContents_udpContent"]/div[2]/div[1]/ul/li[2]'
driver.find_element_by_xpath(xpath_format).click()

# Dataframe으로 변환
temp_list = [x.split(' ') for x in driver.find_element_by_tag_name('table').text.split('\n')] 
temp_data = pd.DataFrame(columns = 
                         ['순위','선수명','팀명','AVG','XBH','GO','AO','GO/AO','GW RBI','BB/K','P/PA','ISOP','XR','GPA']) 
for i,temp in enumerate(temp_list[1:]): 
    # 투수 기록 대비
    try: 
        temp_data.loc[i] = temp 
        time.sleep(0.5) 
    except: 
        ip_index = temp_list[0].index('IP') 
        ip = temp[ip_index] 
        del temp[13] 
        temp[13] = ip+' '+temp[13] 
        temp_data.loc[i] = temp 
        time.sleep(0.5)

baseball_data = pd.merge(baseball_data_test,temp_data,on = ['순위','선수명','팀명','AVG'])

In [3]:
baseball_data

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,XBH,GO,AO,GO/AO,GW RBI,BB/K,P/PA,ISOP,XR,GPA
0,1,이정후,키움,0.360,123,544,464,78,167,42,...,55,131,138,0.95,7,1.68,3.94,0.162,100.8,0.328
1,2,전준우,롯데,0.348,144,619,552,88,192,46,...,53,145,152,0.95,10,0.75,3.64,0.121,98.9,0.300
2,3,강백호,KT,0.347,142,627,516,76,179,40,...,57,131,129,1.02,11,1.21,4.20,0.174,117.6,0.333
3,4,홍창기,LG,0.328,144,651,524,103,172,26,...,32,138,121,1.14,8,1.15,4.17,0.080,106.4,0.307
4,5,박건우,두산,0.325,126,525,458,82,149,31,...,39,111,132,0.84,3,0.69,3.70,0.116,78.9,0.290
5,6,양의지,NC,0.325,141,570,480,81,156,29,...,61,84,190,0.44,17,1.15,3.74,0.256,110.1,0.332
6,7,손아섭,롯데,0.319,139,610,542,88,173,29,...,34,179,124,1.44,9,0.91,3.65,0.077,79.5,0.275
7,8,페르난데스,두산,0.315,141,617,540,73,170,24,...,39,170,171,0.99,4,1.86,3.48,0.128,87.0,0.287
8,9,김선빈,KIA,0.307,130,564,501,55,154,32,...,37,181,132,1.37,7,1.44,3.82,0.094,71.3,0.269
9,10,안치홍,롯데,0.306,119,490,421,58,129,30,...,42,129,114,1.13,9,0.90,4.00,0.152,71.8,0.285
10,11,구자욱,삼성,0.306,139,610,543,107,166,30,...,62,122,169,0.72,9,0.49,3.87,0.214,103.8,0.292
11,12,김혜성,키움,0.304,144,635,559,99,170,20,...,26,165,137,1.20,7,0.67,4.01,0.063,88.0,0.259
12,13,박성한,SSG,0.302,135,471,407,53,123,21,...,26,109,104,1.05,4,0.67,4.01,0.086,62.7,0.267
13,14,이용규,키움,0.296,133,547,459,88,136,16,...,25,152,131,1.16,5,1.54,4.24,0.076,76.0,0.270
14,15,최원준,KIA,0.295,143,668,589,82,174,21,...,31,185,165,1.12,5,0.90,3.82,0.076,86.9,0.260
15,16,정훈,롯데,0.292,135,561,486,70,142,27,...,42,114,144,0.79,6,0.76,4.18,0.146,82.4,0.281
16,17,황재균,KT,0.291,117,507,453,74,132,16,...,28,88,145,0.61,5,0.50,4.02,0.110,65.1,0.262
17,18,박해민,삼성,0.291,127,542,454,78,132,22,...,28,116,131,0.89,5,0.84,4.20,0.086,74.3,0.267
18,19,강민호,삼성,0.291,123,462,406,55,118,22,...,40,129,113,1.14,12,0.85,3.60,0.187,66.6,0.282
19,20,이대호,롯데,0.286,114,465,420,39,120,11,...,30,121,135,0.90,5,0.68,3.69,0.162,63.7,0.266
20,20,피렐라,삼성,0.286,140,621,553,102,158,25,...,56,143,166,0.86,10,0.64,3.76,0.210,96.3,0.285
21,22,오재일,삼성,0.285,120,484,418,64,119,20,...,45,99,102,0.97,9,0.55,3.82,0.227,79.9,0.293
22,23,김현수,LG,0.285,140,595,506,70,144,23,...,41,156,173,0.90,19,1.83,3.79,0.150,88.7,0.278
23,24,정은원,한화,0.283,139,608,495,85,140,22,...,33,126,127,0.99,2,1.00,4.47,0.101,84.2,0.279
24,25,나성범,NC,0.281,144,623,570,96,160,29,...,63,119,140,0.85,9,0.25,3.74,0.228,95.5,0.278
25,26,마차도,롯데,0.279,134,539,466,83,130,21,...,27,133,145,0.92,2,0.89,3.69,0.082,64.4,0.252
26,27,한유섬,SSG,0.278,135,519,442,71,123,18,...,50,108,121,0.89,4,0.63,4.04,0.256,87.5,0.301
27,28,허경민,두산,0.278,136,518,468,61,130,24,...,30,175,131,1.34,6,1.03,3.76,0.088,51.8,0.243
28,29,최정,SSG,0.278,134,555,436,92,121,17,...,53,77,148,0.52,13,0.82,4.02,0.284,105.0,0.325
29,30,채은성,LG,0.276,110,448,387,59,107,20,...,36,89,118,0.75,7,0.48,3.88,0.176,64.6,0.275

In [4]:
driver.close()