In [37]:
import os
from selenium import webdriver 
import time 
import pandas as pd 

webdriver_path = os.getcwd()+'.//webdriver//chromedriver.exe'

url_base = 'https://www.koreabaseball.com/Record/Player/' 
category_list = ['HitterBasic/Basic1.aspx', 'HitterBasic/Detail1.aspx', 'Defense/Basic.aspx'] 
driver = webdriver.Chrome(webdriver_path) 
driver.implicitly_wait(3) 

# 드라이버 열기
driver.get(url_base+category_list[0])

<ipython-input-37-f6414a0df929>:10: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(webdriver_path)

In [41]:
driver.close()

In [38]:
# 정규시즌으로 페이지 넘김
driver.find_element_by_class_name('select02').click()
xpath_format = '//option[@value="0"]'
driver.find_element_by_xpath(xpath_format).click()

In [4]:
driver.find_element_by_class_name('select02').text.split('\n')

['  KBO 정규시즌',
 '  KBO 시범경기',
 '  KBO 와일드카드',
 '  KBO 준플레이오프',
 '  KBO 플레이오프',
 '  KBO 한국시리즈',
 ' ']

In [5]:
data_list=[x.strip() for x in driver.find_element_by_class_name('select02').text.split('\n')]

In [6]:
data_list

['KBO 정규시즌',
 'KBO 시범경기',
 'KBO 와일드카드',
 'KBO 준플레이오프',
 'KBO 플레이오프',
 'KBO 한국시리즈',
 '']

In [7]:
driver.find_element_by_tag_name('table').text.split('\n')

C:\Users\SEC\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:590: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

['순위 선수명 팀명 AVG G PA AB R H 2B 3B HR TB RBI SAC SF',
 '1 이정후 키움 0.360 123 544 464 78 167 42 6 7 242 84 0 9',
 '2 전준우 롯데 0.348 144 619 552 88 192 46 0 7 259 92 1 8',
 '3 강백호 KT 0.347 142 627 516 76 179 40 1 16 269 102 0 8',
 '4 홍창기 LG 0.328 144 651 524 103 172 26 2 4 214 52 0 2',
 '5 박건우 두산 0.325 126 525 458 82 149 31 2 6 202 63 0 6',
 '6 양의지 NC 0.325 141 570 480 81 156 29 2 30 279 111 0 10',
 '7 손아섭 롯데 0.319 139 610 542 88 173 29 2 3 215 58 3 1',
 '8 페르난데스 두산 0.315 141 617 540 73 170 24 0 15 239 81 0 6',
 '9 김선빈 KIA 0.307 130 564 501 55 154 32 0 5 201 67 1 5',
 '10 안치홍 롯데 0.306 119 490 421 58 129 30 2 10 193 82 5 9',
 '11 구자욱 삼성 0.306 139 610 543 107 166 30 10 22 282 88 1 12',
 '12 김혜성 키움 0.304 144 635 559 99 170 20 3 3 205 66 0 10',
 '13 박성한 SSG 0.302 135 471 407 53 123 21 1 4 158 44 12 2',
 '14 이용규 키움 0.296 133 547 459 88 136 16 8 1 171 43 6 6',
 '15 최원준 KIA 0.295 143 668 589 82 174 21 6 4 219 44 4 3',
 '16 정훈 롯데 0.292 135 561 486 70 142 27 1 14 213 79 1 3',
 '17 황재균 KT 0.291 117 507 453 74 132 16 2 10 182 56 1 4',
 '18 박해민 삼성 0.291 127 542 454 78 132 22 1 5 171 54 9 7',
 '19 강민호 삼성 0.291 123 462 406 55 118 22 0 18 194 67 0 7',
 '20 이대호 롯데 0.286 114 465 420 39 120 11 0 19 188 81 0 6',
 '20 피렐라 삼성 0.286 140 621 553 102 158 25 2 29 274 97 0 3',
 '22 오재일 삼성 0.285 120 484 418 64 119 20 0 25 214 97 0 8',
 '23 김현수 LG 0.285 140 595 506 70 144 23 1 17 220 96 0 9',
 '24 정은원 한화 0.283 139 608 495 85 140 22 5 6 190 39 4 3',
 '25 나성범 NC 0.281 144 623 570 96 160 29 1 33 290 101 0 4',
 '26 마차도 롯데 0.279 134 539 466 83 130 21 1 5 168 58 4 7',
 '27 한유섬 SSG 0.278 135 519 442 71 123 18 1 31 236 95 1 6',
 '28 허경민 두산 0.278 136 518 468 61 130 24 1 5 171 59 3 3',
 '29 최정 SSG 0.278 134 555 436 92 121 17 1 35 245 100 1 12',
 '30 채은성 LG 0.276 110 448 387 59 107 20 0 16 175 82 0 7']

In [8]:
temp_list = [x.split(' ') for x in driver.find_element_by_tag_name('table').text.split('\n')]
temp_list

[['순위',
  '선수명',
  '팀명',
  'AVG',
  'G',
  'PA',
  'AB',
  'R',
  'H',
  '2B',
  '3B',
  'HR',
  'TB',
  'RBI',
  'SAC',
  'SF'],
 ['1',
  '이정후',
  '키움',
  '0.360',
  '123',
  '544',
  '464',
  '78',
  '167',
  '42',
  '6',
  '7',
  '242',
  '84',
  '0',
  '9'],
 ['2',
  '전준우',
  '롯데',
  '0.348',
  '144',
  '619',
  '552',
  '88',
  '192',
  '46',
  '0',
  '7',
  '259',
  '92',
  '1',
  '8'],
 ['3',
  '강백호',
  'KT',
  '0.347',
  '142',
  '627',
  '516',
  '76',
  '179',
  '40',
  '1',
  '16',
  '269',
  '102',
  '0',
  '8'],
 ['4',
  '홍창기',
  'LG',
  '0.328',
  '144',
  '651',
  '524',
  '103',
  '172',
  '26',
  '2',
  '4',
  '214',
  '52',
  '0',
  '2'],
 ['5',
  '박건우',
  '두산',
  '0.325',
  '126',
  '525',
  '458',
  '82',
  '149',
  '31',
  '2',
  '6',
  '202',
  '63',
  '0',
  '6'],
 ['6',
  '양의지',
  'NC',
  '0.325',
  '141',
  '570',
  '480',
  '81',
  '156',
  '29',
  '2',
  '30',
  '279',
  '111',
  '0',
  '10'],
 ['7',
  '손아섭',
  '롯데',
  '0.319',
  '139',
  '610',
  '542',
  '88',
  '173',
  '29',
  '2',
  '3',
  '215',
  '58',
  '3',
  '1'],
 ['8',
  '페르난데스',
  '두산',
  '0.315',
  '141',
  '617',
  '540',
  '73',
  '170',
  '24',
  '0',
  '15',
  '239',
  '81',
  '0',
  '6'],
 ['9',
  '김선빈',
  'KIA',
  '0.307',
  '130',
  '564',
  '501',
  '55',
  '154',
  '32',
  '0',
  '5',
  '201',
  '67',
  '1',
  '5'],
 ['10',
  '안치홍',
  '롯데',
  '0.306',
  '119',
  '490',
  '421',
  '58',
  '129',
  '30',
  '2',
  '10',
  '193',
  '82',
  '5',
  '9'],
 ['11',
  '구자욱',
  '삼성',
  '0.306',
  '139',
  '610',
  '543',
  '107',
  '166',
  '30',
  '10',
  '22',
  '282',
  '88',
  '1',
  '12'],
 ['12',
  '김혜성',
  '키움',
  '0.304',
  '144',
  '635',
  '559',
  '99',
  '170',
  '20',
  '3',
  '3',
  '205',
  '66',
  '0',
  '10'],
 ['13',
  '박성한',
  'SSG',
  '0.302',
  '135',
  '471',
  '407',
  '53',
  '123',
  '21',
  '1',
  '4',
  '158',
  '44',
  '12',
  '2'],
 ['14',
  '이용규',
  '키움',
  '0.296',
  '133',
  '547',
  '459',
  '88',
  '136',
  '16',
  '8',
  '1',
  '171',
  '43',
  '6',
  '6'],
 ['15',
  '최원준',
  'KIA',
  '0.295',
  '143',
  '668',
  '589',
  '82',
  '174',
  '21',
  '6',
  '4',
  '219',
  '44',
  '4',
  '3'],
 ['16',
  '정훈',
  '롯데',
  '0.292',
  '135',
  '561',
  '486',
  '70',
  '142',
  '27',
  '1',
  '14',
  '213',
  '79',
  '1',
  '3'],
 ['17',
  '황재균',
  'KT',
  '0.291',
  '117',
  '507',
  '453',
  '74',
  '132',
  '16',
  '2',
  '10',
  '182',
  '56',
  '1',
  '4'],
 ['18',
  '박해민',
  '삼성',
  '0.291',
  '127',
  '542',
  '454',
  '78',
  '132',
  '22',
  '1',
  '5',
  '171',
  '54',
  '9',
  '7'],
 ['19',
  '강민호',
  '삼성',
  '0.291',
  '123',
  '462',
  '406',
  '55',
  '118',
  '22',
  '0',
  '18',
  '194',
  '67',
  '0',
  '7'],
 ['20',
  '이대호',
  '롯데',
  '0.286',
  '114',
  '465',
  '420',
  '39',
  '120',
  '11',
  '0',
  '19',
  '188',
  '81',
  '0',
  '6'],
 ['20',
  '피렐라',
  '삼성',
  '0.286',
  '140',
  '621',
  '553',
  '102',
  '158',
  '25',
  '2',
  '29',
  '274',
  '97',
  '0',
  '3'],
 ['22',
  '오재일',
  '삼성',
  '0.285',
  '120',
  '484',
  '418',
  '64',
  '119',
  '20',
  '0',
  '25',
  '214',
  '97',
  '0',
  '8'],
 ['23',
  '김현수',
  'LG',
  '0.285',
  '140',
  '595',
  '506',
  '70',
  '144',
  '23',
  '1',
  '17',
  '220',
  '96',
  '0',
  '9'],
 ['24',
  '정은원',
  '한화',
  '0.283',
  '139',
  '608',
  '495',
  '85',
  '140',
  '22',
  '5',
  '6',
  '190',
  '39',
  '4',
  '3'],
 ['25',
  '나성범',
  'NC',
  '0.281',
  '144',
  '623',
  '570',
  '96',
  '160',
  '29',
  '1',
  '33',
  '290',
  '101',
  '0',
  '4'],
 ['26',
  '마차도',
  '롯데',
  '0.279',
  '134',
  '539',
  '466',
  '83',
  '130',
  '21',
  '1',
  '5',
  '168',
  '58',
  '4',
  '7'],
 ['27',
  '한유섬',
  'SSG',
  '0.278',
  '135',
  '519',
  '442',
  '71',
  '123',
  '18',
  '1',
  '31',
  '236',
  '95',
  '1',
  '6'],
 ['28',
  '허경민',
  '두산',
  '0.278',
  '136',
  '518',
  '468',
  '61',
  '130',
  '24',
  '1',
  '5',
  '171',
  '59',
  '3',
  '3'],
 ['29',
  '최정',
  'SSG',
  '0.278',
  '134',
  '555',
  '436',
  '92',
  '121',
  '17',
  '1',
  '35',
  '245',
  '100',
  '1',
  '12'],
 ['30',
  '채은성',
  'LG',
  '0.276',
  '110',
  '448',
  '387',
  '59',
  '107',
  '20',
  '0',
  '16',
  '175',
  '82',
  '0',
  '7']]

In [9]:
temp_list[0]

['순위',
 '선수명',
 '팀명',
 'AVG',
 'G',
 'PA',
 'AB',
 'R',
 'H',
 '2B',
 '3B',
 'HR',
 'TB',
 'RBI',
 'SAC',
 'SF']

In [10]:
# Dataframe으로 변환
temp_list = [x.split(' ') for x in driver.find_element_by_tag_name('table').text.split('\n')] 
temp_data = pd.DataFrame(columns = temp_list[0]) 
for i,temp in enumerate(temp_list[1:]): 
    # 투수 기록 대비
    try: 
        temp_data.loc[i] = temp 
        time.sleep(0.5) 
    except: 
        ip_index = temp_list[0].index('IP') 
        ip = temp[ip_index] 
        del temp[13] 
        temp[13] = ip+' '+temp[13] 
        temp_data.loc[i] = temp 
        time.sleep(0.5)

In [14]:
baseball_data = temp_data.copy()

In [12]:
# 넥스트 버튼 누르기
driver.find_element_by_class_name('next').click()

In [15]:
baseball_data

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,3B,HR,TB,RBI,SAC,SF
0,1,이정후,키움,0.360,123,544,464,78,167,42,6,7,242,84,0,9
1,2,전준우,롯데,0.348,144,619,552,88,192,46,0,7,259,92,1,8
2,3,강백호,KT,0.347,142,627,516,76,179,40,1,16,269,102,0,8
3,4,홍창기,LG,0.328,144,651,524,103,172,26,2,4,214,52,0,2
4,5,박건우,두산,0.325,126,525,458,82,149,31,2,6,202,63,0,6
5,6,양의지,NC,0.325,141,570,480,81,156,29,2,30,279,111,0,10
6,7,손아섭,롯데,0.319,139,610,542,88,173,29,2,3,215,58,3,1
7,8,페르난데스,두산,0.315,141,617,540,73,170,24,0,15,239,81,0,6
8,9,김선빈,KIA,0.307,130,564,501,55,154,32,0,5,201,67,1,5
9,10,안치홍,롯데,0.306,119,490,421,58,129,30,2,10,193,82,5,9
10,11,구자욱,삼성,0.306,139,610,543,107,166,30,10,22,282,88,1,12
11,12,김혜성,키움,0.304,144,635,559,99,170,20,3,3,205,66,0,10
12,13,박성한,SSG,0.302,135,471,407,53,123,21,1,4,158,44,12,2
13,14,이용규,키움,0.296,133,547,459,88,136,16,8,1,171,43,6,6
14,15,최원준,KIA,0.295,143,668,589,82,174,21,6,4,219,44,4,3
15,16,정훈,롯데,0.292,135,561,486,70,142,27,1,14,213,79,1,3
16,17,황재균,KT,0.291,117,507,453,74,132,16,2,10,182,56,1,4
17,18,박해민,삼성,0.291,127,542,454,78,132,22,1,5,171,54,9,7
18,19,강민호,삼성,0.291,123,462,406,55,118,22,0,18,194,67,0,7
19,20,이대호,롯데,0.286,114,465,420,39,120,11,0,19,188,81,0,6
20,20,피렐라,삼성,0.286,140,621,553,102,158,25,2,29,274,97,0,3
21,22,오재일,삼성,0.285,120,484,418,64,119,20,0,25,214,97,0,8
22,23,김현수,LG,0.285,140,595,506,70,144,23,1,17,220,96,0,9
23,24,정은원,한화,0.283,139,608,495,85,140,22,5,6,190,39,4,3
24,25,나성범,NC,0.281,144,623,570,96,160,29,1,33,290,101,0,4
25,26,마차도,롯데,0.279,134,539,466,83,130,21,1,5,168,58,4,7
26,27,한유섬,SSG,0.278,135,519,442,71,123,18,1,31,236,95,1,6
27,28,허경민,두산,0.278,136,518,468,61,130,24,1,5,171,59,3,3
28,29,최정,SSG,0.278,134,555,436,92,121,17,1,35,245,100,1,12
29,30,채은성,LG,0.276,110,448,387,59,107,20,0,16,175,82,0,7

In [16]:
driver.find_element_by_tag_name('table').text.split('\n')

C:\Users\SEC\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:590: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

['순위 선수명 팀명 AVG BB IBB HBP SO GDP SLG OBP OPS MH RISP PH-BA',
 '1 이정후 키움 0.360 62 1 9 37 8 0.522 0.438 0.960 51 0.341 0.000',
 '2 전준우 롯데 0.348 53 0 5 71 10 0.469 0.405 0.874 53 0.416 0.600',
 '3 강백호 KT 0.347 103 10 0 85 7 0.521 0.450 0.971 53 0.340 0.000',
 '4 홍창기 LG 0.328 109 4 16 95 6 0.408 0.456 0.864 57 0.343 0.500',
 '5 박건우 두산 0.325 50 2 11 72 16 0.441 0.400 0.841 44 0.325 0.250',
 '6 양의지 NC 0.325 69 5 11 60 12 0.581 0.414 0.995 41 0.374 0.500',
 '7 손아섭 롯데 0.319 61 3 3 67 15 0.397 0.390 0.787 58 0.318 0.000',
 '8 페르난데스 두산 0.315 65 3 6 35 25 0.443 0.391 0.834 48 0.279 0.000',
 '9 김선빈 KIA 0.307 56 2 1 39 19 0.401 0.375 0.776 47 0.320 0.000',
 '10 안치홍 롯데 0.306 52 2 3 58 10 0.458 0.379 0.837 38 0.359 0.500',
 '11 구자욱 삼성 0.306 48 3 6 98 9 0.519 0.361 0.880 45 0.283 0.000',
 '12 김혜성 키움 0.304 65 3 1 97 8 0.367 0.372 0.739 45 0.289 0.500',
 '13 박성한 SSG 0.302 49 0 1 73 1 0.388 0.377 0.765 26 0.298 0.500',
 '14 이용규 키움 0.296 71 2 5 46 5 0.373 0.392 0.765 38 0.276 0.333',
 '15 최원준 KIA 0.295 61 0 11 68 7 0.372 0.370 0.742 46 0.264 0.000',
 '16 정훈 롯데 0.292 68 8 3 89 6 0.438 0.380 0.818 42 0.240 0.167',
 '17 황재균 KT 0.291 46 1 3 92 11 0.402 0.358 0.760 37 0.289 0.000',
 '18 박해민 삼성 0.291 69 2 3 82 3 0.377 0.383 0.760 36 0.327 0.000',
 '19 강민호 삼성 0.291 45 4 4 53 18 0.478 0.361 0.839 34 0.250 0.250',
 '20 이대호 롯데 0.286 34 3 5 50 12 0.448 0.342 0.790 36 0.256 0.143',
 '20 피렐라 삼성 0.286 57 2 8 89 8 0.495 0.359 0.854 52 0.288 0.000',
 '22 오재일 삼성 0.285 58 8 0 106 5 0.512 0.366 0.878 36 0.276 0.000',
 '23 김현수 LG 0.285 77 5 3 42 7 0.435 0.376 0.811 43 0.279 0.000',
 '24 정은원 한화 0.283 105 1 1 105 9 0.384 0.407 0.791 40 0.312 0.500',
 '25 나성범 NC 0.281 38 2 11 155 5 0.509 0.335 0.844 46 0.263 0.000',
 '26 마차도 롯데 0.279 58 1 4 65 9 0.361 0.359 0.720 27 0.339 0.000',
 '27 한유섬 SSG 0.278 60 4 10 96 11 0.534 0.373 0.907 33 0.304 0.429',
 '28 허경민 두산 0.278 36 1 8 35 21 0.365 0.338 0.703 34 0.285 0.444',
 '29 최정 SSG 0.278 84 3 22 102 9 0.562 0.410 0.972 28 0.281 0.600',
 '30 채은성 LG 0.276 38 2 16 80 9 0.452 0.359 0.811 27 0.317 0.167']

In [17]:
# Dataframe으로 변환
temp_list = [x.split(' ') for x in driver.find_element_by_tag_name('table').text.split('\n')] 
temp_data = pd.DataFrame(columns = temp_list[0]) 
for i,temp in enumerate(temp_list[1:]): 
    # 투수 기록 대비
    try: 
        temp_data.loc[i] = temp 
        time.sleep(0.5) 
    except: 
        ip_index = temp_list[0].index('IP') 
        ip = temp[ip_index] 
        del temp[13] 
        temp[13] = ip+' '+temp[13] 
        temp_data.loc[i] = temp 
        time.sleep(0.5)

In [18]:
temp_data

,순위,선수명,팀명,AVG,BB,IBB,HBP,SO,GDP,SLG,OBP,OPS,MH,RISP,PH-BA
0,1,이정후,키움,0.360,62,1,9,37,8,0.522,0.438,0.960,51,0.341,0.000
1,2,전준우,롯데,0.348,53,0,5,71,10,0.469,0.405,0.874,53,0.416,0.600
2,3,강백호,KT,0.347,103,10,0,85,7,0.521,0.450,0.971,53,0.340,0.000
3,4,홍창기,LG,0.328,109,4,16,95,6,0.408,0.456,0.864,57,0.343,0.500
4,5,박건우,두산,0.325,50,2,11,72,16,0.441,0.400,0.841,44,0.325,0.250
5,6,양의지,NC,0.325,69,5,11,60,12,0.581,0.414,0.995,41,0.374,0.500
6,7,손아섭,롯데,0.319,61,3,3,67,15,0.397,0.390,0.787,58,0.318,0.000
7,8,페르난데스,두산,0.315,65,3,6,35,25,0.443,0.391,0.834,48,0.279,0.000
8,9,김선빈,KIA,0.307,56,2,1,39,19,0.401,0.375,0.776,47,0.320,0.000
9,10,안치홍,롯데,0.306,52,2,3,58,10,0.458,0.379,0.837,38,0.359,0.500
10,11,구자욱,삼성,0.306,48,3,6,98,9,0.519,0.361,0.880,45,0.283,0.000
11,12,김혜성,키움,0.304,65,3,1,97,8,0.367,0.372,0.739,45,0.289,0.500
12,13,박성한,SSG,0.302,49,0,1,73,1,0.388,0.377,0.765,26,0.298,0.500
13,14,이용규,키움,0.296,71,2,5,46,5,0.373,0.392,0.765,38,0.276,0.333
14,15,최원준,KIA,0.295,61,0,11,68,7,0.372,0.370,0.742,46,0.264,0.000
15,16,정훈,롯데,0.292,68,8,3,89,6,0.438,0.380,0.818,42,0.240,0.167
16,17,황재균,KT,0.291,46,1,3,92,11,0.402,0.358,0.760,37,0.289,0.000
17,18,박해민,삼성,0.291,69,2,3,82,3,0.377,0.383,0.760,36,0.327,0.000
18,19,강민호,삼성,0.291,45,4,4,53,18,0.478,0.361,0.839,34,0.250,0.250
19,20,이대호,롯데,0.286,34,3,5,50,12,0.448,0.342,0.790,36,0.256,0.143
20,20,피렐라,삼성,0.286,57,2,8,89,8,0.495,0.359,0.854,52,0.288,0.000
21,22,오재일,삼성,0.285,58,8,0,106,5,0.512,0.366,0.878,36,0.276,0.000
22,23,김현수,LG,0.285,77,5,3,42,7,0.435,0.376,0.811,43,0.279,0.000
23,24,정은원,한화,0.283,105,1,1,105,9,0.384,0.407,0.791,40,0.312,0.500
24,25,나성범,NC,0.281,38,2,11,155,5,0.509,0.335,0.844,46,0.263,0.000
25,26,마차도,롯데,0.279,58,1,4,65,9,0.361,0.359,0.720,27,0.339,0.000
26,27,한유섬,SSG,0.278,60,4,10,96,11,0.534,0.373,0.907,33,0.304,0.429
27,28,허경민,두산,0.278,36,1,8,35,21,0.365,0.338,0.703,34,0.285,0.444
28,29,최정,SSG,0.278,84,3,22,102,9,0.562,0.410,0.972,28,0.281,0.600
29,30,채은성,LG,0.276,38,2,16,80,9,0.452,0.359,0.811,27,0.317,0.167

In [19]:
baseball_data

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,3B,HR,TB,RBI,SAC,SF
0,1,이정후,키움,0.360,123,544,464,78,167,42,6,7,242,84,0,9
1,2,전준우,롯데,0.348,144,619,552,88,192,46,0,7,259,92,1,8
2,3,강백호,KT,0.347,142,627,516,76,179,40,1,16,269,102,0,8
3,4,홍창기,LG,0.328,144,651,524,103,172,26,2,4,214,52,0,2
4,5,박건우,두산,0.325,126,525,458,82,149,31,2,6,202,63,0,6
5,6,양의지,NC,0.325,141,570,480,81,156,29,2,30,279,111,0,10
6,7,손아섭,롯데,0.319,139,610,542,88,173,29,2,3,215,58,3,1
7,8,페르난데스,두산,0.315,141,617,540,73,170,24,0,15,239,81,0,6
8,9,김선빈,KIA,0.307,130,564,501,55,154,32,0,5,201,67,1,5
9,10,안치홍,롯데,0.306,119,490,421,58,129,30,2,10,193,82,5,9
10,11,구자욱,삼성,0.306,139,610,543,107,166,30,10,22,282,88,1,12
11,12,김혜성,키움,0.304,144,635,559,99,170,20,3,3,205,66,0,10
12,13,박성한,SSG,0.302,135,471,407,53,123,21,1,4,158,44,12,2
13,14,이용규,키움,0.296,133,547,459,88,136,16,8,1,171,43,6,6
14,15,최원준,KIA,0.295,143,668,589,82,174,21,6,4,219,44,4,3
15,16,정훈,롯데,0.292,135,561,486,70,142,27,1,14,213,79,1,3
16,17,황재균,KT,0.291,117,507,453,74,132,16,2,10,182,56,1,4
17,18,박해민,삼성,0.291,127,542,454,78,132,22,1,5,171,54,9,7
18,19,강민호,삼성,0.291,123,462,406,55,118,22,0,18,194,67,0,7
19,20,이대호,롯데,0.286,114,465,420,39,120,11,0,19,188,81,0,6
20,20,피렐라,삼성,0.286,140,621,553,102,158,25,2,29,274,97,0,3
21,22,오재일,삼성,0.285,120,484,418,64,119,20,0,25,214,97,0,8
22,23,김현수,LG,0.285,140,595,506,70,144,23,1,17,220,96,0,9
23,24,정은원,한화,0.283,139,608,495,85,140,22,5,6,190,39,4,3
24,25,나성범,NC,0.281,144,623,570,96,160,29,1,33,290,101,0,4
25,26,마차도,롯데,0.279,134,539,466,83,130,21,1,5,168,58,4,7
26,27,한유섬,SSG,0.278,135,519,442,71,123,18,1,31,236,95,1,6
27,28,허경민,두산,0.278,136,518,468,61,130,24,1,5,171,59,3,3
28,29,최정,SSG,0.278,134,555,436,92,121,17,1,35,245,100,1,12
29,30,채은성,LG,0.276,110,448,387,59,107,20,0,16,175,82,0,7

In [20]:
baseball_data_test = pd.merge(baseball_data,temp_data,on = ['순위','선수명','팀명','AVG'])
baseball_data_test

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,IBB,HBP,SO,GDP,SLG,OBP,OPS,MH,RISP,PH-BA
0,1,이정후,키움,0.360,123,544,464,78,167,42,...,1,9,37,8,0.522,0.438,0.960,51,0.341,0.000
1,2,전준우,롯데,0.348,144,619,552,88,192,46,...,0,5,71,10,0.469,0.405,0.874,53,0.416,0.600
2,3,강백호,KT,0.347,142,627,516,76,179,40,...,10,0,85,7,0.521,0.450,0.971,53,0.340,0.000
3,4,홍창기,LG,0.328,144,651,524,103,172,26,...,4,16,95,6,0.408,0.456,0.864,57,0.343,0.500
4,5,박건우,두산,0.325,126,525,458,82,149,31,...,2,11,72,16,0.441,0.400,0.841,44,0.325,0.250
5,6,양의지,NC,0.325,141,570,480,81,156,29,...,5,11,60,12,0.581,0.414,0.995,41,0.374,0.500
6,7,손아섭,롯데,0.319,139,610,542,88,173,29,...,3,3,67,15,0.397,0.390,0.787,58,0.318,0.000
7,8,페르난데스,두산,0.315,141,617,540,73,170,24,...,3,6,35,25,0.443,0.391,0.834,48,0.279,0.000
8,9,김선빈,KIA,0.307,130,564,501,55,154,32,...,2,1,39,19,0.401,0.375,0.776,47,0.320,0.000
9,10,안치홍,롯데,0.306,119,490,421,58,129,30,...,2,3,58,10,0.458,0.379,0.837,38,0.359,0.500
10,11,구자욱,삼성,0.306,139,610,543,107,166,30,...,3,6,98,9,0.519,0.361,0.880,45,0.283,0.000
11,12,김혜성,키움,0.304,144,635,559,99,170,20,...,3,1,97,8,0.367,0.372,0.739,45,0.289,0.500
12,13,박성한,SSG,0.302,135,471,407,53,123,21,...,0,1,73,1,0.388,0.377,0.765,26,0.298,0.500
13,14,이용규,키움,0.296,133,547,459,88,136,16,...,2,5,46,5,0.373,0.392,0.765,38,0.276,0.333
14,15,최원준,KIA,0.295,143,668,589,82,174,21,...,0,11,68,7,0.372,0.370,0.742,46,0.264,0.000
15,16,정훈,롯데,0.292,135,561,486,70,142,27,...,8,3,89,6,0.438,0.380,0.818,42,0.240,0.167
16,17,황재균,KT,0.291,117,507,453,74,132,16,...,1,3,92,11,0.402,0.358,0.760,37,0.289,0.000
17,18,박해민,삼성,0.291,127,542,454,78,132,22,...,2,3,82,3,0.377,0.383,0.760,36,0.327,0.000
18,19,강민호,삼성,0.291,123,462,406,55,118,22,...,4,4,53,18,0.478,0.361,0.839,34,0.250,0.250
19,20,이대호,롯데,0.286,114,465,420,39,120,11,...,3,5,50,12,0.448,0.342,0.790,36,0.256,0.143
20,20,피렐라,삼성,0.286,140,621,553,102,158,25,...,2,8,89,8,0.495,0.359,0.854,52,0.288,0.000
21,22,오재일,삼성,0.285,120,484,418,64,119,20,...,8,0,106,5,0.512,0.366,0.878,36,0.276,0.000
22,23,김현수,LG,0.285,140,595,506,70,144,23,...,5,3,42,7,0.435,0.376,0.811,43,0.279,0.000
23,24,정은원,한화,0.283,139,608,495,85,140,22,...,1,1,105,9,0.384,0.407,0.791,40,0.312,0.500
24,25,나성범,NC,0.281,144,623,570,96,160,29,...,2,11,155,5,0.509,0.335,0.844,46,0.263,0.000
25,26,마차도,롯데,0.279,134,539,466,83,130,21,...,1,4,65,9,0.361,0.359,0.720,27,0.339,0.000
26,27,한유섬,SSG,0.278,135,519,442,71,123,18,...,4,10,96,11,0.534,0.373,0.907,33,0.304,0.429
27,28,허경민,두산,0.278,136,518,468,61,130,24,...,1,8,35,21,0.365,0.338,0.703,34,0.285,0.444
28,29,최정,SSG,0.278,134,555,436,92,121,17,...,3,22,102,9,0.562,0.410,0.972,28,0.281,0.600
29,30,채은성,LG,0.276,110,448,387,59,107,20,...,2,16,80,9,0.452,0.359,0.811,27,0.317,0.167

In [24]:
baseball_data_test.to_csv('classic_stat.csv',index=False)

In [34]:
detail = driver.find_element_by_class_name('tab')
li = detail.find_element_by_tag_name('li')

In [35]:
li

In [ ]:
# 상세보기 들어가기
//*[@id="cphContents_cphContents_cphContents_udpContent"]/div[2]/div[1]/ul/li[2]

In [39]:
xpath_format = '//*[@id="cphContents_cphContents_cphContents_udpContent"]/div[2]/div[1]/ul/li[2]'
driver.find_element_by_xpath(xpath_format).click()

In [54]:
# Dataframe으로 변환
temp_list = [x.split(' ') for x in driver.find_element_by_tag_name('table').text.split('\n')] 
temp_data = pd.DataFrame(columns = ['순위','선수명',	'팀명','AVG','XBH','GO','AO','GO/AO','GW RBI','BB/K','P/PA','ISOP','XR','GPA']) 
for i,temp in enumerate(temp_list[1:]): 
    # 투수 기록 대비
    try: 
        temp_data.loc[i] = temp 
        time.sleep(0.5) 
    except: 
        ip_index = temp_list[0].index('IP') 
        ip = temp[ip_index] 
        del temp[13] 
        temp[13] = ip+' '+temp[13] 
        temp_data.loc[i] = temp 
        time.sleep(0.5)

C:\Users\SEC\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:590: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

In [55]:
temp_data

,순위,선수명,팀명,AVG,XBH,GO,AO,GO/AO,GW RBI,BB/K,P/PA,ISOP,XR,GPA
0,1,이정후,키움,0.360,55,131,138,0.95,7,1.68,3.94,0.162,100.8,0.328
1,2,전준우,롯데,0.348,53,145,152,0.95,10,0.75,3.64,0.121,98.9,0.300
2,3,강백호,KT,0.347,57,131,129,1.02,11,1.21,4.20,0.174,117.6,0.333
3,4,홍창기,LG,0.328,32,138,121,1.14,8,1.15,4.17,0.080,106.4,0.307
4,5,박건우,두산,0.325,39,111,132,0.84,3,0.69,3.70,0.116,78.9,0.290
5,6,양의지,NC,0.325,61,84,190,0.44,17,1.15,3.74,0.256,110.1,0.332
6,7,손아섭,롯데,0.319,34,179,124,1.44,9,0.91,3.65,0.077,79.5,0.275
7,8,페르난데스,두산,0.315,39,170,171,0.99,4,1.86,3.48,0.128,87.0,0.287
8,9,김선빈,KIA,0.307,37,181,132,1.37,7,1.44,3.82,0.094,71.3,0.269
9,10,안치홍,롯데,0.306,42,129,114,1.13,9,0.90,4.00,0.152,71.8,0.285
10,11,구자욱,삼성,0.306,62,122,169,0.72,9,0.49,3.87,0.214,103.8,0.292
11,12,김혜성,키움,0.304,26,165,137,1.20,7,0.67,4.01,0.063,88.0,0.259
12,13,박성한,SSG,0.302,26,109,104,1.05,4,0.67,4.01,0.086,62.7,0.267
13,14,이용규,키움,0.296,25,152,131,1.16,5,1.54,4.24,0.076,76.0,0.270
14,15,최원준,KIA,0.295,31,185,165,1.12,5,0.90,3.82,0.076,86.9,0.260
15,16,정훈,롯데,0.292,42,114,144,0.79,6,0.76,4.18,0.146,82.4,0.281
16,17,황재균,KT,0.291,28,88,145,0.61,5,0.50,4.02,0.110,65.1,0.262
17,18,박해민,삼성,0.291,28,116,131,0.89,5,0.84,4.20,0.086,74.3,0.267
18,19,강민호,삼성,0.291,40,129,113,1.14,12,0.85,3.60,0.187,66.6,0.282
19,20,이대호,롯데,0.286,30,121,135,0.90,5,0.68,3.69,0.162,63.7,0.266
20,20,피렐라,삼성,0.286,56,143,166,0.86,10,0.64,3.76,0.210,96.3,0.285
21,22,오재일,삼성,0.285,45,99,102,0.97,9,0.55,3.82,0.227,79.9,0.293
22,23,김현수,LG,0.285,41,156,173,0.90,19,1.83,3.79,0.150,88.7,0.278
23,24,정은원,한화,0.283,33,126,127,0.99,2,1.00,4.47,0.101,84.2,0.279
24,25,나성범,NC,0.281,63,119,140,0.85,9,0.25,3.74,0.228,95.5,0.278
25,26,마차도,롯데,0.279,27,133,145,0.92,2,0.89,3.69,0.082,64.4,0.252
26,27,한유섬,SSG,0.278,50,108,121,0.89,4,0.63,4.04,0.256,87.5,0.301
27,28,허경민,두산,0.278,30,175,131,1.34,6,1.03,3.76,0.088,51.8,0.243
28,29,최정,SSG,0.278,53,77,148,0.52,13,0.82,4.02,0.284,105.0,0.325
29,30,채은성,LG,0.276,36,89,118,0.75,7,0.48,3.88,0.176,64.6,0.275

In [50]:
 driver.find_element_by_tag_name('table').text.split('\n')

C:\Users\SEC\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py:590: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")

['순위 선수명 팀명 AVG XBH GO AO GO/AO GW RBI BB/K P/PA ISOP XR GPA',
 '1 이정후 키움 0.360 55 131 138 0.95 7 1.68 3.94 0.162 100.8 0.328',
 '2 전준우 롯데 0.348 53 145 152 0.95 10 0.75 3.64 0.121 98.9 0.300',
 '3 강백호 KT 0.347 57 131 129 1.02 11 1.21 4.20 0.174 117.6 0.333',
 '4 홍창기 LG 0.328 32 138 121 1.14 8 1.15 4.17 0.080 106.4 0.307',
 '5 박건우 두산 0.325 39 111 132 0.84 3 0.69 3.70 0.116 78.9 0.290',
 '6 양의지 NC 0.325 61 84 190 0.44 17 1.15 3.74 0.256 110.1 0.332',
 '7 손아섭 롯데 0.319 34 179 124 1.44 9 0.91 3.65 0.077 79.5 0.275',
 '8 페르난데스 두산 0.315 39 170 171 0.99 4 1.86 3.48 0.128 87.0 0.287',
 '9 김선빈 KIA 0.307 37 181 132 1.37 7 1.44 3.82 0.094 71.3 0.269',
 '10 안치홍 롯데 0.306 42 129 114 1.13 9 0.90 4.00 0.152 71.8 0.285',
 '11 구자욱 삼성 0.306 62 122 169 0.72 9 0.49 3.87 0.214 103.8 0.292',
 '12 김혜성 키움 0.304 26 165 137 1.20 7 0.67 4.01 0.063 88.0 0.259',
 '13 박성한 SSG 0.302 26 109 104 1.05 4 0.67 4.01 0.086 62.7 0.267',
 '14 이용규 키움 0.296 25 152 131 1.16 5 1.54 4.24 0.076 76.0 0.270',
 '15 최원준 KIA 0.295 31 185 165 1.12 5 0.90 3.82 0.076 86.9 0.260',
 '16 정훈 롯데 0.292 42 114 144 0.79 6 0.76 4.18 0.146 82.4 0.281',
 '17 황재균 KT 0.291 28 88 145 0.61 5 0.50 4.02 0.110 65.1 0.262',
 '18 박해민 삼성 0.291 28 116 131 0.89 5 0.84 4.20 0.086 74.3 0.267',
 '19 강민호 삼성 0.291 40 129 113 1.14 12 0.85 3.60 0.187 66.6 0.282',
 '20 이대호 롯데 0.286 30 121 135 0.90 5 0.68 3.69 0.162 63.7 0.266',
 '20 피렐라 삼성 0.286 56 143 166 0.86 10 0.64 3.76 0.210 96.3 0.285',
 '22 오재일 삼성 0.285 45 99 102 0.97 9 0.55 3.82 0.227 79.9 0.293',
 '23 김현수 LG 0.285 41 156 173 0.90 19 1.83 3.79 0.150 88.7 0.278',
 '24 정은원 한화 0.283 33 126 127 0.99 2 1.00 4.47 0.101 84.2 0.279',
 '25 나성범 NC 0.281 63 119 140 0.85 9 0.25 3.74 0.228 95.5 0.278',
 '26 마차도 롯데 0.279 27 133 145 0.92 2 0.89 3.69 0.082 64.4 0.252',
 '27 한유섬 SSG 0.278 50 108 121 0.89 4 0.63 4.04 0.256 87.5 0.301',
 '28 허경민 두산 0.278 30 175 131 1.34 6 1.03 3.76 0.088 51.8 0.243',
 '29 최정 SSG 0.278 53 77 148 0.52 13 0.82 4.02 0.284 105.0 0.325',
 '30 채은성 LG 0.276 36 89 118 0.75 7 0.48 3.88 0.176 64.6 0.275']

In [56]:
driver.close()

In [57]:
baseball_data = pd.merge(baseball_data_test,temp_data,on = ['순위','선수명','팀명','AVG'])
baseball_data

,순위,선수명,팀명,AVG,G,PA,AB,R,H,2B,...,XBH,GO,AO,GO/AO,GW RBI,BB/K,P/PA,ISOP,XR,GPA
0,1,이정후,키움,0.360,123,544,464,78,167,42,...,55,131,138,0.95,7,1.68,3.94,0.162,100.8,0.328
1,2,전준우,롯데,0.348,144,619,552,88,192,46,...,53,145,152,0.95,10,0.75,3.64,0.121,98.9,0.300
2,3,강백호,KT,0.347,142,627,516,76,179,40,...,57,131,129,1.02,11,1.21,4.20,0.174,117.6,0.333
3,4,홍창기,LG,0.328,144,651,524,103,172,26,...,32,138,121,1.14,8,1.15,4.17,0.080,106.4,0.307
4,5,박건우,두산,0.325,126,525,458,82,149,31,...,39,111,132,0.84,3,0.69,3.70,0.116,78.9,0.290
5,6,양의지,NC,0.325,141,570,480,81,156,29,...,61,84,190,0.44,17,1.15,3.74,0.256,110.1,0.332
6,7,손아섭,롯데,0.319,139,610,542,88,173,29,...,34,179,124,1.44,9,0.91,3.65,0.077,79.5,0.275
7,8,페르난데스,두산,0.315,141,617,540,73,170,24,...,39,170,171,0.99,4,1.86,3.48,0.128,87.0,0.287
8,9,김선빈,KIA,0.307,130,564,501,55,154,32,...,37,181,132,1.37,7,1.44,3.82,0.094,71.3,0.269
9,10,안치홍,롯데,0.306,119,490,421,58,129,30,...,42,129,114,1.13,9,0.90,4.00,0.152,71.8,0.285
10,11,구자욱,삼성,0.306,139,610,543,107,166,30,...,62,122,169,0.72,9,0.49,3.87,0.214,103.8,0.292
11,12,김혜성,키움,0.304,144,635,559,99,170,20,...,26,165,137,1.20,7,0.67,4.01,0.063,88.0,0.259
12,13,박성한,SSG,0.302,135,471,407,53,123,21,...,26,109,104,1.05,4,0.67,4.01,0.086,62.7,0.267
13,14,이용규,키움,0.296,133,547,459,88,136,16,...,25,152,131,1.16,5,1.54,4.24,0.076,76.0,0.270
14,15,최원준,KIA,0.295,143,668,589,82,174,21,...,31,185,165,1.12,5,0.90,3.82,0.076,86.9,0.260
15,16,정훈,롯데,0.292,135,561,486,70,142,27,...,42,114,144,0.79,6,0.76,4.18,0.146,82.4,0.281
16,17,황재균,KT,0.291,117,507,453,74,132,16,...,28,88,145,0.61,5,0.50,4.02,0.110,65.1,0.262
17,18,박해민,삼성,0.291,127,542,454,78,132,22,...,28,116,131,0.89,5,0.84,4.20,0.086,74.3,0.267
18,19,강민호,삼성,0.291,123,462,406,55,118,22,...,40,129,113,1.14,12,0.85,3.60,0.187,66.6,0.282
19,20,이대호,롯데,0.286,114,465,420,39,120,11,...,30,121,135,0.90,5,0.68,3.69,0.162,63.7,0.266
20,20,피렐라,삼성,0.286,140,621,553,102,158,25,...,56,143,166,0.86,10,0.64,3.76,0.210,96.3,0.285
21,22,오재일,삼성,0.285,120,484,418,64,119,20,...,45,99,102,0.97,9,0.55,3.82,0.227,79.9,0.293
22,23,김현수,LG,0.285,140,595,506,70,144,23,...,41,156,173,0.90,19,1.83,3.79,0.150,88.7,0.278
23,24,정은원,한화,0.283,139,608,495,85,140,22,...,33,126,127,0.99,2,1.00,4.47,0.101,84.2,0.279
24,25,나성범,NC,0.281,144,623,570,96,160,29,...,63,119,140,0.85,9,0.25,3.74,0.228,95.5,0.278
25,26,마차도,롯데,0.279,134,539,466,83,130,21,...,27,133,145,0.92,2,0.89,3.69,0.082,64.4,0.252
26,27,한유섬,SSG,0.278,135,519,442,71,123,18,...,50,108,121,0.89,4,0.63,4.04,0.256,87.5,0.301
27,28,허경민,두산,0.278,136,518,468,61,130,24,...,30,175,131,1.34,6,1.03,3.76,0.088,51.8,0.243
28,29,최정,SSG,0.278,134,555,436,92,121,17,...,53,77,148,0.52,13,0.82,4.02,0.284,105.0,0.325
29,30,채은성,LG,0.276,110,448,387,59,107,20,...,36,89,118,0.75,7,0.48,3.88,0.176,64.6,0.275

In [59]:
baseball_data.to_csv('kbo_top30.csv',index=False)