In [1]:
import pandas as pd 
import requests 
from bs4 import BeautifulSoup as bs 

url_base = 'https://www.koreabaseball.com/Record/Player/{category}' 
category_list = ['HitterBasic/Basic1.aspx', 'PitcherBasic/Basic1.aspx', 'Defense/Basic.aspx', 'Runner/Basic.aspx'] 

for category in category_list: 
    url = url_base.format(category = category)
    req = requests.get(url)

    html = req.text
    soup = bs(html,'html.parser')

    temp_table = soup.find('div', {'class':'record_result'})

In [2]:
temp_table

<div class="record_result">
<table cellpadding="0" cellspacing="0" class="tData01 tt" summary="선수 주루기록으로 순위,선수명,팀명,경기,도루시도,도루성공,도루실패,도루성공률,주루사,견제사를 표시합니다">
<colgroup>
<col width="80"/>
<col width="120"/>
<col width="80"/>
<col width="80"/>
<col width="80"/>
<col width="80"/>
<col width="80"/>
<col width="80"/>
<col width="80"/>
<col width="80"/>
</colgroup>
<thead>
<tr>
<th>순위</th>
<th>선수명</th>
<th>팀명</th>
<th><a href="javascript:sort('GAME_CN');" onmouseenter="tooltip(this)" onmouseout="hideTip()" title="경기">G</a></th>
<th><a href="javascript:sort('SBA_CN');" onmouseenter="tooltip(this)" onmouseout="hideTip()" title="도루시도">SBA</a></th>
<th><a href="javascript:sort('SB_CN');" onmouseenter="tooltip(this)" onmouseout="hideTip()" title="도루허용">SB</a></th>
<th><a href="javascript:sort('CS_CN');" onmouseenter="tooltip(this)" onmouseout="hideTip()" title="도루실패">CS</a></th>
<th><a href="javascript:sort('SB_RT');" onmouseenter="tooltip(this)" onmouseout="hideTip()" title="도루성공률">SB%</a></th>
<th><a href="javascript:sort('RO_CN');" onmouseenter="tooltip(this)" onmouseout="hideTip()" title="주루사">OOB</a></th>
<th><a href="javascript:sort('POFF_CN');" onmouseenter="tooltip(this)" onmouseout="hideTip()" title="견제사">PKO</a></th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=67304">김혜성</a></td>
<td>키움</td>
<td data-id="GAME_CN">144</td>
<td data-id="SBA_CN">50</td>
<td data-id="SB_CN">46</td>
<td data-id="CS_CN">4</td>
<td data-id="SB_RT">92.0</td>
<td data-id="RO_CN">4</td>
<td data-id="POFF_CN">1</td>
</tr>
<tr>
<td>2</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=66606">최원준</a></td>
<td>KIA</td>
<td data-id="GAME_CN">143</td>
<td data-id="SBA_CN">53</td>
<td data-id="SB_CN">40</td>
<td data-id="CS_CN">13</td>
<td data-id="SB_RT">75.5</td>
<td data-id="RO_CN">6</td>
<td data-id="POFF_CN">4</td>
</tr>
<tr>
<td>3</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=62415">박해민</a></td>
<td>삼성</td>
<td data-id="GAME_CN">127</td>
<td data-id="SBA_CN">51</td>
<td data-id="SB_CN">36</td>
<td data-id="CS_CN">15</td>
<td data-id="SB_RT">70.6</td>
<td data-id="RO_CN">4</td>
<td data-id="POFF_CN">2</td>
</tr>
<tr>
<td>4</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=62404">구자욱</a></td>
<td>삼성</td>
<td data-id="GAME_CN">139</td>
<td data-id="SBA_CN">31</td>
<td data-id="SB_CN">27</td>
<td data-id="CS_CN">4</td>
<td data-id="SB_RT">87.1</td>
<td data-id="RO_CN">6</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>5</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=50854">최지훈</a></td>
<td>SSG</td>
<td data-id="GAME_CN">136</td>
<td data-id="SBA_CN">32</td>
<td data-id="SB_CN">26</td>
<td data-id="CS_CN">6</td>
<td data-id="SB_RT">81.3</td>
<td data-id="RO_CN">4</td>
<td data-id="POFF_CN">2</td>
</tr>
<tr>
<td>6</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=51817">추신수</a></td>
<td>SSG</td>
<td data-id="GAME_CN">137</td>
<td data-id="SBA_CN">34</td>
<td data-id="SB_CN">25</td>
<td data-id="CS_CN">9</td>
<td data-id="SB_RT">73.5</td>
<td data-id="RO_CN">4</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>7</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=66108">홍창기</a></td>
<td>LG</td>
<td data-id="GAME_CN">144</td>
<td data-id="SBA_CN">31</td>
<td data-id="SB_CN">23</td>
<td data-id="CS_CN">8</td>
<td data-id="SB_RT">74.2</td>
<td data-id="RO_CN">5</td>
<td data-id="POFF_CN">3</td>
</tr>
<tr>
<td>7</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=50458">김지찬</a></td>
<td>삼성</td>
<td data-id="GAME_CN">120</td>
<td data-id="SBA_CN">27</td>
<td data-id="SB_CN">23</td>
<td data-id="CS_CN">4</td>
<td data-id="SB_RT">85.2</td>
<td data-id="RO_CN">4</td>
<td data-id="POFF_CN">1</td>
</tr>
<tr>
<td>7</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=62700">하주석</a></td>
<td>한화</td>
<td data-id="GAME_CN">138</td>
<td data-id="SBA_CN">29</td>
<td data-id="SB_CN">23</td>
<td data-id="CS_CN">6</td>
<td data-id="SB_RT">79.3</td>
<td data-id="RO_CN">6</td>
<td data-id="POFF_CN">2</td>
</tr>
<tr>
<td>10</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=66209">조수행</a></td>
<td>두산</td>
<td data-id="GAME_CN">115</td>
<td data-id="SBA_CN">25</td>
<td data-id="SB_CN">21</td>
<td data-id="CS_CN">4</td>
<td data-id="SB_RT">84.0</td>
<td data-id="RO_CN">2</td>
<td data-id="POFF_CN">1</td>
</tr>
<tr>
<td>11</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=50923">알테어</a></td>
<td>NC</td>
<td data-id="GAME_CN">143</td>
<td data-id="SBA_CN">25</td>
<td data-id="SB_CN">20</td>
<td data-id="CS_CN">5</td>
<td data-id="SB_RT">80.0</td>
<td data-id="RO_CN">5</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>12</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=64166">배정대</a></td>
<td>KT</td>
<td data-id="GAME_CN">144</td>
<td data-id="SBA_CN">26</td>
<td data-id="SB_CN">19</td>
<td data-id="CS_CN">7</td>
<td data-id="SB_RT">73.1</td>
<td data-id="RO_CN">2</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>12</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=68743">정은원</a></td>
<td>한화</td>
<td data-id="GAME_CN">139</td>
<td data-id="SBA_CN">30</td>
<td data-id="SB_CN">19</td>
<td data-id="CS_CN">11</td>
<td data-id="SB_RT">63.3</td>
<td data-id="RO_CN">6</td>
<td data-id="POFF_CN">1</td>
</tr>
<tr>
<td>14</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=74163">이용규</a></td>
<td>키움</td>
<td data-id="GAME_CN">133</td>
<td data-id="SBA_CN">19</td>
<td data-id="SB_CN">17</td>
<td data-id="CS_CN">2</td>
<td data-id="SB_RT">89.5</td>
<td data-id="RO_CN">3</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>15</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=64006">심우준</a></td>
<td>KT</td>
<td data-id="GAME_CN">139</td>
<td data-id="SBA_CN">22</td>
<td data-id="SB_CN">16</td>
<td data-id="CS_CN">6</td>
<td data-id="SB_RT">72.7</td>
<td data-id="RO_CN">3</td>
<td data-id="POFF_CN">1</td>
</tr>
<tr>
<td>16</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=65462">김기환</a></td>
<td>NC</td>
<td data-id="GAME_CN">62</td>
<td data-id="SBA_CN">19</td>
<td data-id="SB_CN">15</td>
<td data-id="CS_CN">4</td>
<td data-id="SB_RT">78.9</td>
<td data-id="RO_CN">3</td>
<td data-id="POFF_CN">3</td>
</tr>
<tr>
<td>16</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=64012">송민섭</a></td>
<td>KT</td>
<td data-id="GAME_CN">122</td>
<td data-id="SBA_CN">16</td>
<td data-id="SB_CN">15</td>
<td data-id="CS_CN">1</td>
<td data-id="SB_RT">93.8</td>
<td data-id="RO_CN">0</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>18</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=79215">박건우</a></td>
<td>두산</td>
<td data-id="GAME_CN">126</td>
<td data-id="SBA_CN">13</td>
<td data-id="SB_CN">13</td>
<td data-id="CS_CN">0</td>
<td data-id="SB_RT">100</td>
<td data-id="RO_CN">6</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>18</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=63704">노수광</a></td>
<td>한화</td>
<td data-id="GAME_CN">52</td>
<td data-id="SBA_CN">14</td>
<td data-id="SB_CN">13</td>
<td data-id="CS_CN">1</td>
<td data-id="SB_RT">92.9</td>
<td data-id="RO_CN">5</td>
<td data-id="POFF_CN">1</td>
</tr>
<tr>
<td>20</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=62907">박민우</a></td>
<td>NC</td>
<td data-id="GAME_CN">50</td>
<td data-id="SBA_CN">15</td>
<td data-id="SB_CN">12</td>
<td data-id="CS_CN">3</td>
<td data-id="SB_RT">80.0</td>
<td data-id="RO_CN">3</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>20</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=79231">정수빈</a></td>
<td>두산</td>
<td data-id="GAME_CN">104</td>
<td data-id="SBA_CN">19</td>
<td data-id="SB_CN">12</td>
<td data-id="CS_CN">7</td>
<td data-id="SB_RT">63.2</td>
<td data-id="RO_CN">1</td>
<td data-id="POFF_CN">3</td>
</tr>
<tr>
<td>20</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=64868">조용호</a></td>
<td>KT</td>
<td data-id="GAME_CN">138</td>
<td data-id="SBA_CN">21</td>
<td data-id="SB_CN">12</td>
<td data-id="CS_CN">9</td>
<td data-id="SB_RT">57.1</td>
<td data-id="RO_CN">1</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>20</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=78168">서건창</a></td>
<td>LG</td>
<td data-id="GAME_CN">144</td>
<td data-id="SBA_CN">16</td>
<td data-id="SB_CN">12</td>
<td data-id="CS_CN">4</td>
<td data-id="SB_RT">75.0</td>
<td data-id="RO_CN">3</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>20</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=79109">오지환</a></td>
<td>LG</td>
<td data-id="GAME_CN">134</td>
<td data-id="SBA_CN">18</td>
<td data-id="SB_CN">12</td>
<td data-id="CS_CN">6</td>
<td data-id="SB_RT">66.7</td>
<td data-id="RO_CN">6</td>
<td data-id="POFF_CN">2</td>
</tr>
<tr>
<td>20</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=67893">박성한</a></td>
<td>SSG</td>
<td data-id="GAME_CN">135</td>
<td data-id="SBA_CN">17</td>
<td data-id="SB_CN">12</td>
<td data-id="CS_CN">5</td>
<td data-id="SB_RT">70.6</td>
<td data-id="RO_CN">3</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>26</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=76313">황재균</a></td>
<td>KT</td>
<td data-id="GAME_CN">117</td>
<td data-id="SBA_CN">15</td>
<td data-id="SB_CN">11</td>
<td data-id="CS_CN">4</td>
<td data-id="SB_RT">73.3</td>
<td data-id="RO_CN">4</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>26</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=77532">손아섭</a></td>
<td>롯데</td>
<td data-id="GAME_CN">139</td>
<td data-id="SBA_CN">17</td>
<td data-id="SB_CN">11</td>
<td data-id="CS_CN">6</td>
<td data-id="SB_RT">64.7</td>
<td data-id="RO_CN">7</td>
<td data-id="POFF_CN">0</td>
</tr>
<tr>
<td>28</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=69992">최정원</a></td>
<td>NC</td>
<td data-id="GAME_CN">72</td>
<td data-id="SBA_CN">17</td>
<td data-id="SB_CN">10</td>
<td data-id="CS_CN">7</td>
<td data-id="SB_RT">58.8</td>
<td data-id="RO_CN">1</td>
<td data-id="POFF_CN">1</td>
</tr>
<tr>
<td>28</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=68050">강백호</a></td>
<td>KT</td>
<td data-id="GAME_CN">142</td>
<td data-id="SBA_CN">15</td>
<td data-id="SB_CN">10</td>
<td data-id="CS_CN">5</td>
<td data-id="SB_RT">66.7</td>
<td data-id="RO_CN">10</td>
<td data-id="POFF_CN">2</td>
</tr>
<tr>
<td>28</td>
<td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=67341">이정후</a></td>
<td>키움</td>
<td data-id="GAME_CN">123</td>
<td data-id="SBA_CN">13</td>
<td data-id="SB_CN">10</td>
<td data-id="CS_CN">3</td>
<td data-id="SB_RT">76.9</td>
<td data-id="RO_CN">2</td>
<td data-id="POFF_CN">1</td>
</tr>
</tbody>
</table>
<div class="paging">
<a href="javascript:__doPostBack('ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$ucPager$btnFirst','')" id="cphContents_cphContents_cphContents_ucPager_btnFirst" title="첫 페이지로 이동"><img alt="처음으로" src="//lgcxydabfbch3774324.cdn.ntruss.com/KBO_IMAGE/KBOHome/resources/images/common/btn_paging_first.gif"/></a>
<a class="on" href="javascript:__doPostBack('ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$ucPager$btnNo1','')" id="cphContents_cphContents_cphContents_ucPager_btnNo1">1</a>
<a href="javascript:__doPostBack('ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$ucPager$btnNo2','')" id="cphContents_cphContents_cphContents_ucPager_btnNo2">2</a>
<a href="javascript:__doPostBack('ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$ucPager$btnNo3','')" id="cphContents_cphContents_cphContents_ucPager_btnNo3">3</a>
<a href="javascript:__doPostBack('ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$ucPager$btnNo4','')" id="cphContents_cphContents_cphContents_ucPager_btnNo4">4</a>
<a href="javascript:__doPostBack('ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$ucPager$btnNo5','')" id="cphContents_cphContents_cphContents_ucPager_btnNo5">5</a>
<a href="javascript:__doPostBack('ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$ucPager$btnNext','')" id="cphContents_cphContents_cphContents_ucPager_btnNext" title="다음 페이지로 이동"><img alt="다음" src="//lgcxydabfbch3774324.cdn.ntruss.com/KBO_IMAGE/KBOHome/resources/images/common/btn_paging_next.gif"/></a>
<a href="javascript:__doPostBack('ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$ucPager$btnLast','')" id="cphContents_cphContents_cphContents_ucPager_btnLast" title="마지막 페이지로 이동"><img alt="맨끝으로" src="//lgcxydabfbch3774324.cdn.ntruss.com/KBO_IMAGE/KBOHome/resources/images/common/btn_paging_last.gif"/></a>
</div>
<input id="cphContents_cphContents_cphContents_hfPage" name="ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$hfPage" type="hidden" value="1"/>
<input id="cphContents_cphContents_cphContents_hfOrderByCol" name="ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$hfOrderByCol" type="hidden" value="SB_CN"/>
<input id="cphContents_cphContents_cphContents_hfOrderBy" name="ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$hfOrderBy" type="hidden" value="DESC"/>
<a href="javascript:__doPostBack('ctl00$ctl00$ctl00$cphContents$cphContents$cphContents$lbtnOrderBy','')" id="cphContents_cphContents_cphContents_lbtnOrderBy" style="display:none"></a>
</div>

In [3]:
import pandas as pd 
import requests 
from bs4 import BeautifulSoup as bs 

url_base = 'https://www.koreabaseball.com/Record/Player/{category}' 
category_list = ['HitterBasic/Basic1.aspx', 'PitcherBasic/Basic1.aspx', 'Defense/Basic.aspx', 'Runner/Basic.aspx'] 

for category in category_list: 
    url = url_base.format(category = category)
    req = requests.get(url)

    html = req.text
    soup = bs(html,'html.parser')

    temp_table = soup.find('div', {'class':'record_result'})

    col_tag = temp_table.find_all('td')

In [4]:
# rank name team 뿐
col_tag

[<td>1</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=67304">김혜성</a></td>,
 <td>키움</td>,
 <td data-id="GAME_CN">144</td>,
 <td data-id="SBA_CN">50</td>,
 <td data-id="SB_CN">46</td>,
 <td data-id="CS_CN">4</td>,
 <td data-id="SB_RT">92.0</td>,
 <td data-id="RO_CN">4</td>,
 <td data-id="POFF_CN">1</td>,
 <td>2</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=66606">최원준</a></td>,
 <td>KIA</td>,
 <td data-id="GAME_CN">143</td>,
 <td data-id="SBA_CN">53</td>,
 <td data-id="SB_CN">40</td>,
 <td data-id="CS_CN">13</td>,
 <td data-id="SB_RT">75.5</td>,
 <td data-id="RO_CN">6</td>,
 <td data-id="POFF_CN">4</td>,
 <td>3</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=62415">박해민</a></td>,
 <td>삼성</td>,
 <td data-id="GAME_CN">127</td>,
 <td data-id="SBA_CN">51</td>,
 <td data-id="SB_CN">36</td>,
 <td data-id="CS_CN">15</td>,
 <td data-id="SB_RT">70.6</td>,
 <td data-id="RO_CN">4</td>,
 <td data-id="POFF_CN">2</td>,
 <td>4</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=62404">구자욱</a></td>,
 <td>삼성</td>,
 <td data-id="GAME_CN">139</td>,
 <td data-id="SBA_CN">31</td>,
 <td data-id="SB_CN">27</td>,
 <td data-id="CS_CN">4</td>,
 <td data-id="SB_RT">87.1</td>,
 <td data-id="RO_CN">6</td>,
 <td data-id="POFF_CN">0</td>,
 <td>5</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=50854">최지훈</a></td>,
 <td>SSG</td>,
 <td data-id="GAME_CN">136</td>,
 <td data-id="SBA_CN">32</td>,
 <td data-id="SB_CN">26</td>,
 <td data-id="CS_CN">6</td>,
 <td data-id="SB_RT">81.3</td>,
 <td data-id="RO_CN">4</td>,
 <td data-id="POFF_CN">2</td>,
 <td>6</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=51817">추신수</a></td>,
 <td>SSG</td>,
 <td data-id="GAME_CN">137</td>,
 <td data-id="SBA_CN">34</td>,
 <td data-id="SB_CN">25</td>,
 <td data-id="CS_CN">9</td>,
 <td data-id="SB_RT">73.5</td>,
 <td data-id="RO_CN">4</td>,
 <td data-id="POFF_CN">0</td>,
 <td>7</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=66108">홍창기</a></td>,
 <td>LG</td>,
 <td data-id="GAME_CN">144</td>,
 <td data-id="SBA_CN">31</td>,
 <td data-id="SB_CN">23</td>,
 <td data-id="CS_CN">8</td>,
 <td data-id="SB_RT">74.2</td>,
 <td data-id="RO_CN">5</td>,
 <td data-id="POFF_CN">3</td>,
 <td>7</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=50458">김지찬</a></td>,
 <td>삼성</td>,
 <td data-id="GAME_CN">120</td>,
 <td data-id="SBA_CN">27</td>,
 <td data-id="SB_CN">23</td>,
 <td data-id="CS_CN">4</td>,
 <td data-id="SB_RT">85.2</td>,
 <td data-id="RO_CN">4</td>,
 <td data-id="POFF_CN">1</td>,
 <td>7</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=62700">하주석</a></td>,
 <td>한화</td>,
 <td data-id="GAME_CN">138</td>,
 <td data-id="SBA_CN">29</td>,
 <td data-id="SB_CN">23</td>,
 <td data-id="CS_CN">6</td>,
 <td data-id="SB_RT">79.3</td>,
 <td data-id="RO_CN">6</td>,
 <td data-id="POFF_CN">2</td>,
 <td>10</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=66209">조수행</a></td>,
 <td>두산</td>,
 <td data-id="GAME_CN">115</td>,
 <td data-id="SBA_CN">25</td>,
 <td data-id="SB_CN">21</td>,
 <td data-id="CS_CN">4</td>,
 <td data-id="SB_RT">84.0</td>,
 <td data-id="RO_CN">2</td>,
 <td data-id="POFF_CN">1</td>,
 <td>11</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=50923">알테어</a></td>,
 <td>NC</td>,
 <td data-id="GAME_CN">143</td>,
 <td data-id="SBA_CN">25</td>,
 <td data-id="SB_CN">20</td>,
 <td data-id="CS_CN">5</td>,
 <td data-id="SB_RT">80.0</td>,
 <td data-id="RO_CN">5</td>,
 <td data-id="POFF_CN">0</td>,
 <td>12</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=64166">배정대</a></td>,
 <td>KT</td>,
 <td data-id="GAME_CN">144</td>,
 <td data-id="SBA_CN">26</td>,
 <td data-id="SB_CN">19</td>,
 <td data-id="CS_CN">7</td>,
 <td data-id="SB_RT">73.1</td>,
 <td data-id="RO_CN">2</td>,
 <td data-id="POFF_CN">0</td>,
 <td>12</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=68743">정은원</a></td>,
 <td>한화</td>,
 <td data-id="GAME_CN">139</td>,
 <td data-id="SBA_CN">30</td>,
 <td data-id="SB_CN">19</td>,
 <td data-id="CS_CN">11</td>,
 <td data-id="SB_RT">63.3</td>,
 <td data-id="RO_CN">6</td>,
 <td data-id="POFF_CN">1</td>,
 <td>14</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=74163">이용규</a></td>,
 <td>키움</td>,
 <td data-id="GAME_CN">133</td>,
 <td data-id="SBA_CN">19</td>,
 <td data-id="SB_CN">17</td>,
 <td data-id="CS_CN">2</td>,
 <td data-id="SB_RT">89.5</td>,
 <td data-id="RO_CN">3</td>,
 <td data-id="POFF_CN">0</td>,
 <td>15</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=64006">심우준</a></td>,
 <td>KT</td>,
 <td data-id="GAME_CN">139</td>,
 <td data-id="SBA_CN">22</td>,
 <td data-id="SB_CN">16</td>,
 <td data-id="CS_CN">6</td>,
 <td data-id="SB_RT">72.7</td>,
 <td data-id="RO_CN">3</td>,
 <td data-id="POFF_CN">1</td>,
 <td>16</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=65462">김기환</a></td>,
 <td>NC</td>,
 <td data-id="GAME_CN">62</td>,
 <td data-id="SBA_CN">19</td>,
 <td data-id="SB_CN">15</td>,
 <td data-id="CS_CN">4</td>,
 <td data-id="SB_RT">78.9</td>,
 <td data-id="RO_CN">3</td>,
 <td data-id="POFF_CN">3</td>,
 <td>16</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=64012">송민섭</a></td>,
 <td>KT</td>,
 <td data-id="GAME_CN">122</td>,
 <td data-id="SBA_CN">16</td>,
 <td data-id="SB_CN">15</td>,
 <td data-id="CS_CN">1</td>,
 <td data-id="SB_RT">93.8</td>,
 <td data-id="RO_CN">0</td>,
 <td data-id="POFF_CN">0</td>,
 <td>18</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=79215">박건우</a></td>,
 <td>두산</td>,
 <td data-id="GAME_CN">126</td>,
 <td data-id="SBA_CN">13</td>,
 <td data-id="SB_CN">13</td>,
 <td data-id="CS_CN">0</td>,
 <td data-id="SB_RT">100</td>,
 <td data-id="RO_CN">6</td>,
 <td data-id="POFF_CN">0</td>,
 <td>18</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=63704">노수광</a></td>,
 <td>한화</td>,
 <td data-id="GAME_CN">52</td>,
 <td data-id="SBA_CN">14</td>,
 <td data-id="SB_CN">13</td>,
 <td data-id="CS_CN">1</td>,
 <td data-id="SB_RT">92.9</td>,
 <td data-id="RO_CN">5</td>,
 <td data-id="POFF_CN">1</td>,
 <td>20</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=62907">박민우</a></td>,
 <td>NC</td>,
 <td data-id="GAME_CN">50</td>,
 <td data-id="SBA_CN">15</td>,
 <td data-id="SB_CN">12</td>,
 <td data-id="CS_CN">3</td>,
 <td data-id="SB_RT">80.0</td>,
 <td data-id="RO_CN">3</td>,
 <td data-id="POFF_CN">0</td>,
 <td>20</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=79231">정수빈</a></td>,
 <td>두산</td>,
 <td data-id="GAME_CN">104</td>,
 <td data-id="SBA_CN">19</td>,
 <td data-id="SB_CN">12</td>,
 <td data-id="CS_CN">7</td>,
 <td data-id="SB_RT">63.2</td>,
 <td data-id="RO_CN">1</td>,
 <td data-id="POFF_CN">3</td>,
 <td>20</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=64868">조용호</a></td>,
 <td>KT</td>,
 <td data-id="GAME_CN">138</td>,
 <td data-id="SBA_CN">21</td>,
 <td data-id="SB_CN">12</td>,
 <td data-id="CS_CN">9</td>,
 <td data-id="SB_RT">57.1</td>,
 <td data-id="RO_CN">1</td>,
 <td data-id="POFF_CN">0</td>,
 <td>20</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=78168">서건창</a></td>,
 <td>LG</td>,
 <td data-id="GAME_CN">144</td>,
 <td data-id="SBA_CN">16</td>,
 <td data-id="SB_CN">12</td>,
 <td data-id="CS_CN">4</td>,
 <td data-id="SB_RT">75.0</td>,
 <td data-id="RO_CN">3</td>,
 <td data-id="POFF_CN">0</td>,
 <td>20</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=79109">오지환</a></td>,
 <td>LG</td>,
 <td data-id="GAME_CN">134</td>,
 <td data-id="SBA_CN">18</td>,
 <td data-id="SB_CN">12</td>,
 <td data-id="CS_CN">6</td>,
 <td data-id="SB_RT">66.7</td>,
 <td data-id="RO_CN">6</td>,
 <td data-id="POFF_CN">2</td>,
 <td>20</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=67893">박성한</a></td>,
 <td>SSG</td>,
 <td data-id="GAME_CN">135</td>,
 <td data-id="SBA_CN">17</td>,
 <td data-id="SB_CN">12</td>,
 <td data-id="CS_CN">5</td>,
 <td data-id="SB_RT">70.6</td>,
 <td data-id="RO_CN">3</td>,
 <td data-id="POFF_CN">0</td>,
 <td>26</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=76313">황재균</a></td>,
 <td>KT</td>,
 <td data-id="GAME_CN">117</td>,
 <td data-id="SBA_CN">15</td>,
 <td data-id="SB_CN">11</td>,
 <td data-id="CS_CN">4</td>,
 <td data-id="SB_RT">73.3</td>,
 <td data-id="RO_CN">4</td>,
 <td data-id="POFF_CN">0</td>,
 <td>26</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=77532">손아섭</a></td>,
 <td>롯데</td>,
 <td data-id="GAME_CN">139</td>,
 <td data-id="SBA_CN">17</td>,
 <td data-id="SB_CN">11</td>,
 <td data-id="CS_CN">6</td>,
 <td data-id="SB_RT">64.7</td>,
 <td data-id="RO_CN">7</td>,
 <td data-id="POFF_CN">0</td>,
 <td>28</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=69992">최정원</a></td>,
 <td>NC</td>,
 <td data-id="GAME_CN">72</td>,
 <td data-id="SBA_CN">17</td>,
 <td data-id="SB_CN">10</td>,
 <td data-id="CS_CN">7</td>,
 <td data-id="SB_RT">58.8</td>,
 <td data-id="RO_CN">1</td>,
 <td data-id="POFF_CN">1</td>,
 <td>28</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=68050">강백호</a></td>,
 <td>KT</td>,
 <td data-id="GAME_CN">142</td>,
 <td data-id="SBA_CN">15</td>,
 <td data-id="SB_CN">10</td>,
 <td data-id="CS_CN">5</td>,
 <td data-id="SB_RT">66.7</td>,
 <td data-id="RO_CN">10</td>,
 <td data-id="POFF_CN">2</td>,
 <td>28</td>,
 <td><a href="/Record/Player/HitterDetail/Basic.aspx?playerId=67341">이정후</a></td>,
 <td>키움</td>,
 <td data-id="GAME_CN">123</td>,
 <td data-id="SBA_CN">13</td>,
 <td data-id="SB_CN">10</td>,
 <td data-id="CS_CN">3</td>,
 <td data-id="SB_RT">76.9</td>,
 <td data-id="RO_CN">2</td>,
 <td data-id="POFF_CN">1</td>]

In [5]:
import pandas as pd 
import requests 
from bs4 import BeautifulSoup as bs 

url_base = 'https://www.koreabaseball.com/Record/Player/{category}' 
category_list = ['HitterBasic/Basic1.aspx', 'PitcherBasic/Basic1.aspx', 'Defense/Basic.aspx', 'Runner/Basic.aspx'] 

data_list = []
for category in category_list: 
    url = url_base.format(category = category)
    req = requests.get(url)

    html = req.text
    soup = bs(html,'html.parser')

    temp_table = soup.find('div', {'class':'record_result'})

    col_tag = temp_table.find_all('td') 
    
    col_list = ['Rank', 'Name', 'Team']

    for col in col_tag:
        try:
            temp_value = col.attrs['data-id']
            if temp_value not in col_list:
                col_list.append(temp_value)
            else:
                break
        except:
            pass
    temp_data = pd.DataFrame(columns = col_list)

    i = 0
    index = 0
    col_len = len(col_list)
    while True:
        try:
            temp_data.loc[i] = [x.text for x in temp_table.find_all('td')[index:index + col_len]]
            i += 1
            index += col_len
        except:
            break
    
    data_list.append(temp_data)

In [6]:
data_list

[Empty DataFrame
 Columns: [Rank, Name, Team]
 Index: [], Empty DataFrame
 Columns: [Rank, Name, Team]
 Index: [],    Rank Name Team POS_SC GAME_CN  ... FPCT_RT PB_CN SB_CN CS_CN CS_RT
 0     1  배정대   KT    중견수     144  ...   0.991     0     0     0     -
 1     2  최원준  KIA    우익수     140  ...   0.977     0     0     0     -
 2     3  심우준   KT    유격수     138  ...   0.966     0     0     0     -
 3     4  알테어   NC    중견수     134  ...   0.994     0     0     0     -
 4     4  손아섭   롯데    우익수     134  ...   0.978     0     0     0     -
 5     6  강백호   KT    1루수     133  ...   0.983     0     0     0     -
 6     6  마차도   롯데    유격수     133  ...   0.981     0     0     0     -
 7     8  오지환   LG    유격수     132  ...   0.976     0     0     0     -
 8     9  나성범   NC    우익수     131  ...   0.979     0     0     0     -
 9     9  서건창   LG    2루수     131  ...   0.986     0     0     0     -
 10   11  허경민   두산    3루수     130  ...   0.969     0     0     0     -
 11   11  구자욱   삼성    우익수     130  ...   0.988     0     0     0     -
 12   11  김상수   삼성    2루수     130  ...   0.980     0     0     0     -
 13   14  유강남   LG     포수     129  ...   0.997     9    77    23  23.0
 14   14  박성한  SSG    유격수     129  ...   0.957     0     0     0     -
 15   16  박찬호  KIA    유격수     128  ...   0.956     0     0     0     -
 16   16   최정  SSG    3루수     128  ...   0.961     0     0     0     -
 17   18  양석환   두산    1루수     127  ...   0.991     0     0     0     -
 18   19  김재환   두산    좌익수     126  ...   0.981     0     0     0     -
 19   20  김선빈  KIA    2루수     125  ...   0.986     0     0     0     -
 20   20  박해민   삼성    중견수     125  ...   0.996     0     0     0     -
 21   20  정은원   한화    2루수     125  ...   0.975     0     0     0     -
 22   23  한동희   롯데    3루수     124  ...   0.953     0     0     0     -
 23   24  강진성   NC    1루수     120  ...   0.986     0     0     0     -
 24   25  강민호   삼성     포수     119  ...   0.992     3    40    11  21.6
 25   26  김민성   LG    3루수     117  ...   0.970     0     0     0     -
 26   26  오재일   삼성    1루수     117  ...   0.998     0     0     0     -
 27   28  홍창기   LG    중견수     116  ...   0.990     0     0     0     -
 28   28  전준우   롯데    좌익수     116  ...   1.000     0     0     0     -
 29   28  김강민  SSG    중견수     116  ...   0.987     0     0     0     -

 [30 rows x 17 columns],    Rank Name Team GAME_CN SBA_CN SB_CN CS_CN SB_RT RO_CN POFF_CN
 0     1  김혜성   키움     144     50    46     4  92.0     4       1
 1     2  최원준  KIA     143     53    40    13  75.5     6       4
 2     3  박해민   삼성     127     51    36    15  70.6     4       2
 3     4  구자욱   삼성     139     31    27     4  87.1     6       0
 4     5  최지훈  SSG     136     32    26     6  81.3     4       2
 5     6  추신수  SSG     137     34    25     9  73.5     4       0
 6     7  홍창기   LG     144     31    23     8  74.2     5       3
 7     7  김지찬   삼성     120     27    23     4  85.2     4       1
 8     7  하주석   한화     138     29    23     6  79.3     6       2
 9    10  조수행   두산     115     25    21     4  84.0     2       1
 10   11  알테어   NC     143     25    20     5  80.0     5       0
 11   12  배정대   KT     144     26    19     7  73.1     2       0
 12   12  정은원   한화     139     30    19    11  63.3     6       1
 13   14  이용규   키움     133     19    17     2  89.5     3       0
 14   15  심우준   KT     139     22    16     6  72.7     3       1
 15   16  김기환   NC      62     19    15     4  78.9     3       3
 16   16  송민섭   KT     122     16    15     1  93.8     0       0
 17   18  박건우   두산     126     13    13     0   100     6       0
 18   18  노수광   한화      52     14    13     1  92.9     5       1
 19   20  박민우   NC      50     15    12     3  80.0     3       0
 20   20  정수빈   두산     104     19    12     7  63.2     1       3
 21   20  조용호   KT     138     21    12     9  57.1     1       0
 22   20  서건창   LG     144     16    12     4  75.0     3       0
 23   20  오지환   LG     134     18    12     6  66.7     6       2
 24   20  박성한  SSG     135     17    12     5  70.6     3       0
 25   26  황재균   KT     117     15    11     4  73.3     4       0
 26   26  손아섭   롯데     139     17    11     6  64.7     7       0
 27   28  최정원   NC      72     17    10     7  58.8     1       1
 28   28  강백호   KT     142     15    10     5  66.7    10       2
 29   28  이정후   키움     123     13    10     3  76.9     2       1]

In [7]:
data_list[3]

   Rank Name Team GAME_CN SBA_CN SB_CN CS_CN SB_RT RO_CN POFF_CN
0     1  김혜성   키움     144     50    46     4  92.0     4       1
1     2  최원준  KIA     143     53    40    13  75.5     6       4
2     3  박해민   삼성     127     51    36    15  70.6     4       2
3     4  구자욱   삼성     139     31    27     4  87.1     6       0
4     5  최지훈  SSG     136     32    26     6  81.3     4       2
5     6  추신수  SSG     137     34    25     9  73.5     4       0
6     7  홍창기   LG     144     31    23     8  74.2     5       3
7     7  김지찬   삼성     120     27    23     4  85.2     4       1
8     7  하주석   한화     138     29    23     6  79.3     6       2
9    10  조수행   두산     115     25    21     4  84.0     2       1
10   11  알테어   NC     143     25    20     5  80.0     5       0
11   12  배정대   KT     144     26    19     7  73.1     2       0
12   12  정은원   한화     139     30    19    11  63.3     6       1
13   14  이용규   키움     133     19    17     2  89.5     3       0
14   15  심우준   KT     139     22    16     6  72.7     3       1
15   16  김기환   NC      62     19    15     4  78.9     3       3
16   16  송민섭   KT     122     16    15     1  93.8     0       0
17   18  박건우   두산     126     13    13     0   100     6       0
18   18  노수광   한화      52     14    13     1  92.9     5       1
19   20  박민우   NC      50     15    12     3  80.0     3       0
20   20  정수빈   두산     104     19    12     7  63.2     1       3
21   20  조용호   KT     138     21    12     9  57.1     1       0
22   20  서건창   LG     144     16    12     4  75.0     3       0
23   20  오지환   LG     134     18    12     6  66.7     6       2
24   20  박성한  SSG     135     17    12     5  70.6     3       0
25   26  황재균   KT     117     15    11     4  73.3     4       0
26   26  손아섭   롯데     139     17    11     6  64.7     7       0
27   28  최정원   NC      72     17    10     7  58.8     1       1
28   28  강백호   KT     142     15    10     5  66.7    10       2
29   28  이정후   키움     123     13    10     3  76.9     2       1

In [8]:
df = pd.DataFrame(data_list[3])

### 왜 타격정보가 안넘어오지?