<a href="https://colab.research.google.com/github/ujaei21/TIL/blob/master/mlb_pitch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/jldbc/pybaseball

Cloning into 'pybaseball'...
remote: Enumerating objects: 2410, done.
remote: Counting objects: 100% (236/236), done.
remote: Compressing objects: 100% (172/172), done.
remote: Total 2410 (delta 113), reused 130 (delta 61), pack-reused 2174
Receiving objects: 100% (2410/2410), 6.62 MiB | 14.74 MiB/s, done.
Resolving deltas: 100% (1426/1426), done.

In [ ]:
cd /content/pybaseball

/content/pybaseball

In [ ]:
pip install -e .

Obtaining file:///content/pybaseball
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pyarrow>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (3.0.0)
Requirement already satisfied: attrs>=20.3.0 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (21.2.0)
Requirement already satisfied: lxml>=4.2.1 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (4.2.6)
Requirement already satisfied: pandas>=1.0.3 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (1.1.5)
Requirement already satisfied: scipy>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (1.4.1)
Requirement already satisfied: numpy>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (1.19.5)
Requirement already satisfied: beautifulsoup4>=4.4.0 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (4.6.3)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (3.2.2)
Requirement already satisfied: tqdm>=4.50.0 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (4.62.3)
Requirement already satisfied: requests>=2.18.1 in /usr/local/lib/python3.7/dist-packages (from pybaseball==2.2.1) (2.23.0)
Collecting pygithub>=1.51
  Downloading PyGithub-1.55-py3-none-any.whl (291 kB)
     |████████████████████████████████| 291 kB 5.2 MB/s
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->pybaseball==2.2.1) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->pybaseball==2.2.1) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->pybaseball==2.2.1) (1.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=2.0.0->pybaseball==2.2.1) (3.0.6)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.3->pybaseball==2.2.1) (2018.9)
Collecting pynacl>=1.4.0
  Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
     |████████████████████████████████| 961 kB 49.9 MB/s
Collecting deprecated
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting pyjwt>=2.0
  Downloading PyJWT-2.3.0-py3-none-any.whl (16 kB)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from pynacl>=1.4.0->pygithub>=1.51->pybaseball==2.2.1) (1.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from pynacl>=1.4.0->pygithub>=1.51->pybaseball==2.2.1) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.4.1->pynacl>=1.4.0->pygithub>=1.51->pybaseball==2.2.1) (2.21)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.1->pybaseball==2.2.1) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.1->pybaseball==2.2.1) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.1->pybaseball==2.2.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.18.1->pybaseball==2.2.1) (2021.10.8)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.7/dist-packages (from deprecated->pygithub>=1.51->pybaseball==2.2.1) (1.13.3)
Installing collected packages: pynacl, pyjwt, deprecated, pygithub, pybaseball
  Running setup.py develop for pybaseball
Successfully installed deprecated-1.2.13 pybaseball-2.2.1 pygithub-1.55 pyjwt-2.3.0 pynacl-1.4.0

In [ ]:
from pybaseball import statcast

In [ ]:
from pybaseball import playerid_lookup
from pybaseball import statcast_pitcher

# ryu	hyun jin	547943
playerid_lookup('ryu', 'hyun jin')

Gathering player lookup table. This may take a moment.

  name_last name_first  ...  mlb_played_first mlb_played_last
0       ryu   hyun jin  ...            2013.0          2021.0

[1 rows x 8 columns]

In [ ]:
# 게릿 콜  cole	gerrit	543037	
playerid_lookup('cole')

   name_last name_first  ...  mlb_played_first mlb_played_last
0       cole      a. j.  ...            2015.0          2021.0
1       cole       alex  ...            1990.0          1996.0
2       cole     archie  ...            1923.0          1924.0
3       cole       bert  ...            1921.0          1927.0
4       cole      cecil  ...            1946.0          1946.0
5       cole       dave  ...            1950.0          1955.0
6       cole       dick  ...            1951.0          1957.0
7       cole         ed  ...            1938.0          1939.0
8       cole     gerrit  ...            2013.0          2021.0
9       cole       king  ...            1909.0          1915.0
10      cole        stu  ...            1991.0          1991.0
11      cole     taylor  ...            2017.0          2019.0
12      cole     victor  ...            1992.0          1992.0
13      cole     willis  ...            1909.0          1910.0

[14 rows x 8 columns]

In [ ]:
ryu_stats = statcast_pitcher('2021-04-01', '2021-10-3',547943)
ryu_stats.head(5)

Gathering Player Data

  pitch_type   game_date  ...  delta_home_win_exp  delta_run_exp
0         CH  2021-10-03  ...               0.005         -0.430
1         FF  2021-10-03  ...               0.000         -0.237
2         FF  2021-10-03  ...               0.000         -0.139
3         CU  2021-10-03  ...              -0.003          0.307
4         CH  2021-10-03  ...               0.000         -0.137

[5 rows x 92 columns]

In [ ]:
ryu_stats.game_date.nunique()

31

In [ ]:
result=ryu_stats[['pitch_name','game_date','release_speed','release_pos_x','release_pos_y','release_pos_z','release_spin_rate','release_extension','spin_axis']]

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(result)

           pitch_name   game_date  ...  release_extension  spin_axis
0            Changeup  2021-10-03  ...                6.6      105.0
1     4-Seam Fastball  2021-10-03  ...                6.6      125.0
2     4-Seam Fastball  2021-10-03  ...                6.5      132.0
3           Curveball  2021-10-03  ...                6.5      320.0
4            Changeup  2021-10-03  ...                6.9      113.0
...               ...         ...  ...                ...        ...
2684  4-Seam Fastball  2021-04-01  ...                6.5      136.0
2685           Cutter  2021-04-01  ...                6.4      157.0
2686  4-Seam Fastball  2021-04-01  ...                6.4      144.0
2687           Cutter  2021-04-01  ...                6.3      166.0
2688  4-Seam Fastball  2021-04-01  ...                6.3      141.0

[2689 rows x 9 columns]

In [ ]:
result.pitch_name.unique()

array(['Changeup', '4-Seam Fastball', 'Curveball', 'Cutter', 'Sinker',
       'Slider'], dtype=object)

In [ ]:
result.groupby(['pitch_name','game_date']).std().round(2)

                            release_speed  ...  spin_axis
pitch_name      game_date                  ...
4-Seam Fastball 2021-04-01           1.37  ...       3.54
                2021-04-07           1.27  ...       4.85
                2021-04-13           0.89  ...       3.69
                2021-04-20           1.09  ...      10.51
                2021-04-25           0.97  ...       3.81
...                                   ...  ...        ...
Slider          2021-05-12           1.39  ...      20.40
                2021-05-18           0.08  ...      17.56
                2021-05-23            NaN  ...        NaN
                2021-05-28           1.33  ...      47.38
                2021-06-26            NaN  ...        NaN

[131 rows x 7 columns]

In [ ]:
result

           pitch_name   game_date  ...  release_extension  spin_axis
0            Changeup  2021-10-03  ...                6.6      105.0
1     4-Seam Fastball  2021-10-03  ...                6.6      125.0
2     4-Seam Fastball  2021-10-03  ...                6.5      132.0
3           Curveball  2021-10-03  ...                6.5      320.0
4            Changeup  2021-10-03  ...                6.9      113.0
...               ...         ...  ...                ...        ...
2684  4-Seam Fastball  2021-04-01  ...                6.5      136.0
2685           Cutter  2021-04-01  ...                6.4      157.0
2686  4-Seam Fastball  2021-04-01  ...                6.4      144.0
2687           Cutter  2021-04-01  ...                6.3      166.0
2688  4-Seam Fastball  2021-04-01  ...                6.3      141.0

[2689 rows x 9 columns]

In [ ]:
result[result['pitch_name']=='4-Seam Fastball']

           pitch_name   game_date  ...  release_extension  spin_axis
1     4-Seam Fastball  2021-10-03  ...                6.6      125.0
2     4-Seam Fastball  2021-10-03  ...                6.5      132.0
5     4-Seam Fastball  2021-10-03  ...                6.8      126.0
6     4-Seam Fastball  2021-10-03  ...                6.6      124.0
11    4-Seam Fastball  2021-10-03  ...                6.6      127.0
...               ...         ...  ...                ...        ...
2678  4-Seam Fastball  2021-04-01  ...                6.7      134.0
2679  4-Seam Fastball  2021-04-01  ...                6.6      135.0
2684  4-Seam Fastball  2021-04-01  ...                6.5      136.0
2686  4-Seam Fastball  2021-04-01  ...                6.4      144.0
2688  4-Seam Fastball  2021-04-01  ...                6.3      141.0

[966 rows x 9 columns]

In [ ]:
ff = result[result['pitch_name']=='4-Seam Fastball']

In [ ]:
# 페스트볼의 편차
ff.groupby(['pitch_name','game_date'],as_index=False).std().round(2)

         pitch_name   game_date  ...  release_extension  spin_axis
0   4-Seam Fastball  2021-04-01  ...               0.16       3.54
1   4-Seam Fastball  2021-04-07  ...               0.16       4.85
2   4-Seam Fastball  2021-04-13  ...               0.12       3.69
3   4-Seam Fastball  2021-04-20  ...               0.09      10.51
4   4-Seam Fastball  2021-04-25  ...               0.10       3.81
5   4-Seam Fastball  2021-05-06  ...               0.14       4.64
6   4-Seam Fastball  2021-05-12  ...               0.08       3.64
7   4-Seam Fastball  2021-05-18  ...               0.11       3.88
8   4-Seam Fastball  2021-05-23  ...               0.09       6.37
9   4-Seam Fastball  2021-05-28  ...               0.12       4.98
10  4-Seam Fastball  2021-06-04  ...               0.10       3.49
11  4-Seam Fastball  2021-06-10  ...               0.11       4.18
12  4-Seam Fastball  2021-06-15  ...               0.11       3.78
13  4-Seam Fastball  2021-06-20  ...               0.10       6.24
14  4-Seam Fastball  2021-06-26  ...               0.09       2.81
15  4-Seam Fastball  2021-07-01  ...               0.10       3.37
16  4-Seam Fastball  2021-07-07  ...               0.13       4.68
17  4-Seam Fastball  2021-07-18  ...               0.10       2.69
18  4-Seam Fastball  2021-07-24  ...               0.08       3.13
19  4-Seam Fastball  2021-07-29  ...               0.12       3.26
20  4-Seam Fastball  2021-08-03  ...               0.14       3.10
21  4-Seam Fastball  2021-08-08  ...               0.09       4.99
22  4-Seam Fastball  2021-08-14  ...               0.12       4.45
23  4-Seam Fastball  2021-08-21  ...               0.12       4.68
24  4-Seam Fastball  2021-08-26  ...               0.10       4.09
25  4-Seam Fastball  2021-08-31  ...               0.12       3.80
26  4-Seam Fastball  2021-09-06  ...               0.25       3.04
27  4-Seam Fastball  2021-09-11  ...               0.14       2.23
28  4-Seam Fastball  2021-09-17  ...               0.07       3.26
29  4-Seam Fastball  2021-09-28  ...               0.12       4.19
30  4-Seam Fastball  2021-10-03  ...               0.20       4.31

[31 rows x 9 columns]

### 체인지업과 직구의 편차비교